### PR TITLE
fix: Move upgrade-time abandonExports responsibility into the kernel

### LINKED ISSUE #6696: have the kernel abandon non-durable vat exports during upgrade, not `stopVat`
## What is the Problem Being Solved?

As listed in #6650, during vat upgrade, one of the last remaining responsiblities of the old vat's `stopVat` call has been to abandon all non-durable exports. We need to abandon these here, because clients may still have imports that refer to them (Presences), but the implementation of these objects will not be available after the upgrade (not being durable). By calling `syscall.abandonExport()` on the vrefs, the old vat is telling the kernel to treat those objects as unowned by any vat. They retain their identity, and refcounts will keep the kref alive as usual, but any attempt to send them a message will result in an error being generated by the kernel (aka "message goes splat"), and the objects will be removed from the old exporting vat's c-list.

The task is to move this responsibility into the kernel. During `processUpgradeVat`, the kernel will enumerate the upgraded vat's c-list for all non-durable exports (which, after #6695, ~will be the set of kvStore keys from `${vatID}.o+/` through `${vatID}.o+e`~ edit: durables are `o+d..`, so I think non-durables are `o+/`-`o+:`, plus `o+v`-`o+v:`). For each one, it will do the same thing as `syscall.abandonExports` (currently implemented in `kernelSyscall.js`): a `kernelKeeper.orphanKernelObject(koid, vatID)`. It must also delete the c-list entry (currently performed in `vatTranslator.js` in the `translateAbandonExports()` function).

Simultaneously, we should remove the `abandonExports()` call from `src/liveslots/stop-vat.js`.

### PR DESCRIPTION
**Pull request by gibson042**
Stacked on #7130

Closes: #6696

## Description

Adds to `processUpgradeVat` simulation of an abandonExports syscall from the incarnation being terminated, in order to clean up state even if stopVat is broken.

TODO:
- [ ] Add the white-box reachable/recognizable test described at https://github.com/Agoric/agoric-sdk/issues/6696#issuecomment-1431881255
   > prepare one export that is held strongly by a downstream vat (so the export-side c-list entry is marked as "R" for Reachable), then the upstream vat does a `syscall.abandonExports` on it, and the test asserts that the c-list entry is deleted... also prepare an export that is held _weakly_ by a downstream vat (so the c-list entry is marked as `_` for merely-Recognizable), and assert that `syscall.abandonExports` deletes the c-list entry, and also delivers a `dispatch.retireExports` to the downstream vat. Look at https://github.com/Agoric/agoric-sdk/blob/f6996583c94e4b1d61160a102f1e92f81cc27bb0/packages/SwingSet/test/test-abandon-export.js .

### Security Considerations

There is arguably a layering violation in simulation of the abandonExports, but the current state arguably already has similar violations (e.g., manipulation of vat c-lists in `translateAbandonExports` that is independent of table manipulation in `abandonExports`). I decided to duplicate the combined effects manually in `processUpgradeVat` to avoid manifestation of spurious sycalls, and left breadcrumbs in the upstream sites to keep everything in sync. It would might be good to abstract the underlying manipulations, but I'm not in a position to do so until the layers are clearly articulated (perhaps as part of #7161).

### Scaling Considerations

I don't think this PR meaningfully affects scaling, although I did observe what is probably an unnecessary amount of preexisting vat–kernel translation. The new `enumerateNonDurableObjectExports` function I'm introducing returns {kref, vref} records, which might be a good pattern for more widespread adoption.

There's also the open question of whether `stopVat` should opportunistically remain for vat-local reference collection that is beyond kernel visibility, without which I think we can end up leaking unreachable durable objects. I've currently left the pieces in place but commented them out so testing verifies that the kernel does a good enough job without cooperation from the vat.

### Documentation Considerations

Working on this required reviewing lots of somewhat stale and sometimes misleading SwingSet/Liveslots documentation (and I still don't think I've got a good handle on https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/docs/garbage-collection.md , which is super dense). A big cleanup effort would be great, but in the meantime I'll submit a relatively small PR.

### Testing Considerations

I'll see what things look like when I get to the more elaborate test.

### CODE REVIEW

File: packages/SwingSet/src/kernel/state/storageHelper.js [hunk 1]
```diff
@@ -2,15 +2,26 @@
...
-export function* enumeratePrefixedKeys(kvStore, prefix) {
-  // return an iterator of all existing keys that start with
-  // ${prefix}, in lexicographic order, excluding ${prefix} itself
+/**
+ * Iterate over keys with a given prefix, in lexicographic order,
+ * excluding an exact match of the prefix.
+ *
+ * @param {KVStore} kvStore
+ * @param {string} prefix
+ * @param {string} [exclusiveEnd]
```
Comment (warner) [inline packages/SwingSet/src/kernel/state/storageHelper.js:11]: let's add a unit test for the new argument in test-state.js

File: packages/SwingSet/test/upgrade/test-upgrade.js [hunk 2]
```diff
@@ -34,73 +36,130 @@ const dumpState = (debug, vatID) => {
...
+ * @param {import('ava').ExecutionContext} t
+ * @param {object} bundleData
+ * @param {SwingSetConfig} config
+ * @returns {{
+ *   controller: ReturnType<typeof makeSwingsetController>,
+ *   kvStore: KVStore,
+ *   run: (method: string, args?: unknown[]) => Promise<unknown>,
+ * }}
+ */
+const initKernelForTest = async (t, bundleData, config) => {
```
Comment (warner) [inline packages/SwingSet/test/upgrade/test-upgrade.js]: I like this refactoring!

**Review by warner — APPROVED** [review]
Nice job! Looks good to me, modulo the test of the new `enumeratePrefixKeys` argument.

Are you thinking of opening a separate ticket for the remaining `retireExports` test? Let's either do that, or remove the "closes NNN" line from this PR's first comment, so it doesn't accidentally close the ticket. I think the `retireExports` test is important; we wouldn't want to discover (late) that it causes an upgrade to crash.

**Comment by gibson042** [comment]
> Are you thinking of opening a separate ticket for the remaining `retireExports` test? Let's either do that, or remove the "closes NNN" line from this PR's first comment, so it doesn't accidentally close the ticket. I think the `retireExports` test is important; we wouldn't want to discover (late) that it causes an upgrade to crash.

Agreed. It's a TODO task in this PR that I'm working on now.

File: packages/swingset-liveslots/src/stop-vat.js [hunk 3]
```diff
@@ -285,10 +288,15 @@ export async function releaseOldState(tools) {
...
 
-  const abandonedVrefSet = new Set();
-  identifyExportedRemotables(abandonedVrefSet, tools);
-  identifyExportedFacets(abandonedVrefSet, tools);
-  abandonExports(abandonedVrefSet, tools);
+  // TODO: Decide how much (if any) cleanup to do here in the vat.
+  // The kernel simulates abandonExports as part of vat upgrade,
+  // but does not decrement vat-side refcounts which could allow us to
+  // drop durable objects that were only being kept alive by references from
+  // non-durable objects.
```
Comment (gibson042) [inline packages/swingset-liveslots/src/stop-vat.js:295]: @warner any specific thoughts on this?

**Comment by gibson042** [comment]
@warner You sure have a knack for requesting fiendishly difficult testing. I've got what I think is a good framework in place, but I'm never seeing `dispatch.retireExports`, even if I restore the liveslots stopVat changes (and if I'm reading https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/docs/garbage-collection.md#syscallabandonexport-processing correctly, that might be expected). Let's try to work through this together on Monday.

**Comment by gibson042** [comment]
The current state is that changes to kernel.js and stop-vat.js remove the abandonExports syscall from a liveslots-style vat being upgraded but do not otherwise affect the delivery/syscall log (as expected), but they also result in failure to clear the owner of an object from a setup-style vat being upgraded (again without affecting the delivery/syscall log). So I think my code intended to simulate the abandonExports syscall isn't quite right and the current task is to track down its deviation from correct behavior.

<details><summary>liveslots-style vat</summary>

```diff
diff --git 1/log.test-upgrade.liveslots.master.txt 2/log.test-upgrade.liveslots.pr.txt
index 7c741fe4e..e3c76608e 100644
--- 1/log.test-upgrade.liveslots.master.txt
+++ 2/log.test-upgrade.liveslots.pr.txt
@@ -985,149 +985,138 @@ DELIVERY.vd notify [
 SYSCALL send ko27 {
   methargs: {
     body: '#["upgrade",["$0.Alleged: device node",{"vatParameters":{"version":"v2"}}]]',
     slots: [ 'kd31' ]
   },
   result: 'kp65'
 }
 SYSCALL subscribe v1 kp65
 SYSCALL vatstoreSet v1 idCounters {"exportID":20,"collectionID":7,"promiseID":17}
 DELIVERY { crankNum: 125n, vatID: 'v1', deliveryNum: 49n }
 DELIVERY.kd bringOutYourDead
 DELIVERY.vd bringOutYourDead
 DEQUEUE {
   type: 'send',
   target: 'ko27',
   msg: {
     methargs: {
       body: '#["upgrade",["$0.Alleged: device node",{"vatParameters":{"version":"v2"}}]]',
       slots: [Array]
     },
     result: 'kp65'
   }
 }
 DELIVERY { crankNum: 126n, vatID: 'v2', deliveryNum: 12n }
 DELIVERY.kd message ko27 {
   methargs: {
     body: '#["upgrade",["$0.Alleged: device node",{"vatParameters":{"version":"v2"}}]]',
     slots: [ 'kd31' ]
   },
   result: 'kp65'
 }
 DELIVERY.vd message o+d13/1 {
   methargs: {
     body: '#["upgrade",["$0.Alleged: device node",{"vatParameters":{"version":"v2"}}]]',
     slots: [ 'd-71' ]
   },
   result: 'p-65'
 }
 SYSCALL invoke kd31 getBundleID { body: '#[]', slots: [] }
 SYSCALL vatstoreGet d7 slot.d+1
 SYSCALL invoke kd30 upgradeVat {
   body: '#["v6","b1-bb828dd6b8b5a6011187c92664331e660f9d260ffad9e97c90fd7b935e761c549ffa4e12b4514e842f91cc41750079e0a70dc37a75a29c5b74a0c70b47bb0cfc",{"version":"v2"},"vat upgraded"]',
   slots: []
 }
 SYSCALL callKernelHook d7 upgrade {
   body: '#["v6","b1-bb828dd6b8b5a6011187c92664331e660f9d260ffad9e97c90fd7b935e761c549ffa4e12b4514e842f91cc41750079e0a70dc37a75a29c5b74a0c70b47bb0cfc",{"version":"v2"},"vat upgraded"]',
   slots: []
 }
 DELIVERY { crankNum: 128n, vatID: 'v2', deliveryNum: 13n }
 DELIVERY.kd bringOutYourDead
 DELIVERY.vd bringOutYourDead
 DEQUEUE {
   type: 'upgrade-vat',
   vatID: 'v6',
   upgradeID: 'up1',
   bundleID: 'b1-bb828dd6b8b5a6011187c92664331e660f9d260ffad9e97c90fd7b935e761c549ffa4e12b4514e842f91cc41750079e0a70dc37a75a29c5b74a0c70b47bb0cfc',
   vatParameters: { body: '#{"version":"v2"}', slots: [] },
   upgradeMessage: 'vat upgraded'
 }
 DELIVERY { crankNum: 129n, vatID: 'v6', deliveryNum: 16n }
 DELIVERY.kd stopVat {
   body: '#{"incarnationNumber":1,"name":"vatUpgraded","upgradeMessage":"vat upgraded"}',
   slots: []
 }
 DELIVERY.vd stopVat {
   body: '#{"incarnationNumber":1,"name":"vatUpgraded","upgradeMessage":"vat upgraded"}',
   slots: []
 }
-SYSCALL vatstoreGetNextKey v6 vom.es.
-SYSCALL vatstoreGet v6 vom.es.o+d11/1
-SYSCALL vatstoreGetNextKey v6 vom.es.o+d11/1
-SYSCALL vatstoreGet v6 vom.es.o+v10/1
-SYSCALL vatstoreGetNextKey v6 vom.es.o+v10/1
-SYSCALL vatstoreGet v6 vom.es.o+v10/1
-SYSCALL vatstoreSet v6 vom.es.o+v10/1 s
-SYSCALL vatstoreGet v6 vom.rc.o+v10/1
-SYSCALL vatstoreGet v6 vom.es.o+v10/1
-SYSCALL vatstoreDelete v6 vom.es.o+v10/1
-SYSCALL abandonExports v6 [ 'ko28', 'ko29' ]
 DELIVERY { crankNum: 129n, vatID: 'v6', deliveryNum: 17n }
 DELIVERY.kd startVat { body: '#{"version":"v2"}', slots: [] }
 DELIVERY.vd startVat { body: '#{"version":"v2"}', slots: [] }
 SYSCALL vatstoreGet v6 idCounters
 SYSCALL vatstoreGet v6 kindIDID
 SYSCALL vatstoreGet v6 storeKindIDTable
 SYSCALL vatstoreSet v6 storeKindIDTable {"scalarMapStore":2,"scalarWeakMapStore":3,"scalarSetStore":4,"scalarWeakSetStore":5,"scalarDurableMapStore":6,"scalarDurableWeakMapStore":7,"scalarDurableSetStore":8,"scalarDurableWeakSetStore":9}
 SYSCALL vatstoreGet v6 baggageID
 SYSCALL vatstoreGet v6 vc.1.|schemata
 SYSCALL vatstoreGet v6 vc.1.|label
 SYSCALL vatstoreSet v6 vc.5.|nextOrdinal 1
 SYSCALL vatstoreSet v6 vc.5.|entryCount 0
 SYSCALL vatstoreSet v6 vc.5.|schemata {"body":"#[{\"#tag\":\"match:scalar\",\"payload\":\"#undefined\"}]","slots":[]}
 SYSCALL vatstoreSet v6 vc.5.|label promiseRegistrations
 SYSCALL vatstoreGet v6 watcherTableID
 SYSCALL vatstoreGet v6 vc.3.|schemata
 SYSCALL vatstoreGet v6 vc.3.|label
 SYSCALL vatstoreGet v6 watchedPromiseTableID
 SYSCALL vatstoreGet v6 vc.4.|schemata
 SYSCALL vatstoreGet v6 vc.4.|label
 SYSCALL vatstoreSet v6 vom.vkind.13 {"kindID":"13","tag":"VirtualCounter"}
 SYSCALL vatstoreGet v6 vc.1.sDurableCounter_kindHandle
 SYSCALL vatstoreGet v6 vc.1.sDurableCounter_kindHandle
 SYSCALL vatstoreGet v6 vom.dkind.11
 SYSCALL vatstoreGet v6 vc.1.sdurableCounter
 SYSCALL vatstoreGet v6 vc.1.sdurableCounter
 SYSCALL vatstoreGet v6 vom.o+d11/1
 SYSCALL vatstoreGet v6 vc.4.
 SYSCALL vatstoreGetNextKey v6 vc.4.
 SYSCALL vatstoreGetNextKey v6 vom.dkind.
 SYSCALL vatstoreGet v6 vom.dkind.11
 SYSCALL vatstoreGetNextKey v6 vom.dkind.11
 SYSCALL vatstoreSet v6 idCounters {"exportID":14,"collectionID":6,"promiseID":5}
 DEQUEUE {
   type: 'send',
   target: 'ko20',
   msg: {
     methargs: {
       body: '#["vatUpgradeCallback",["up1",true,"#undefined",2]]',
       slots: []
     },
     result: 'kp66'
   }
 }
 DELIVERY { crankNum: 131n, vatID: 'v2', deliveryNum: 14n }
 DELIVERY.kd message ko20 {
   methargs: {
     body: '#["vatUpgradeCallback",["up1",true,"#undefined",2]]',
     slots: []
   },
   result: 'kp66'
 }
 DELIVERY.vd message o+0 {
   methargs: {
     body: '#["vatUpgradeCallback",["up1",true,"#undefined",2]]',
     slots: []
   },
   result: 'p-66'
 }
 SYSCALL resolve v2 [ [ 'kp66', false, { body: '#"#undefined"', slots: [] } ] ]
 SYSCALL resolve v2 [ [ 'kp65', false, { body: '#{"incarnationNumber":2}', slots: [] } ] ]
 DELIVERY { crankNum: 133n, vatID: 'v2', deliveryNum: 15n }
 DELIVERY.kd bringOutYourDead
 DELIVERY.vd bringOutYourDead
 DEQUEUE { type: 'notify', vatID: 'v1', kpid: 'kp65' }
 DELIVERY { crankNum: 134n, vatID: 'v1', deliveryNum: 50n }
 DELIVERY.kd notify [ [ 'kp65', { state: 'fulfilled', data: [Object] } ] ]
 DELIVERY.vd notify [ [ 'p+16', false, { body: '#{"incarnationNumber":2}', slots: [] } ] ]
 SYSCALL resolve v1 [ [ 'kp63', false, { body: '#{"incarnationNumber":2}', slots: [] } ] ]
 DELIVERY { crankNum: 135n, vatID: 'v1', deliveryNum: 51n }
@@ -1322,74 +1311,74 @@ Error: vat terminated
 RemoteError#2 ERROR_NOTE: Sent as error:liveSlots:v1#70002
 SYSCALL resolve v1 [
   [
     'kp71',
     true,
     {
       body: '#{"#error":"vat terminated","errorId":"error:liveSlots:v1#70002","name":"Error"}',
       slots: []
     }
   ]
 ]
 DELIVERY { crankNum: 158n, vatID: 'v1', deliveryNum: 63n }
 DELIVERY.kd bringOutYourDead
 DELIVERY.vd bringOutYourDead
 DEQUEUE {
   type: 'send',
   target: 'ko21',
   msg: {
     methargs: {
       body: '#["messageVatObject",[{"methodName":"increment","presence":"%replaced:3"}]]',
       slots: []
     },
     result: 'kp73'
   }
 }
 DELIVERY { crankNum: 160n, vatID: 'v1', deliveryNum: 64n }
 DELIVERY.kd message ko21 {
   methargs: {
     body: '#["messageVatObject",[{"methodName":"increment","presence":"%replaced:3"}]]',
     slots: []
   },
   result: 'kp73'
 }
 DELIVERY.vd message o+0 {
   methargs: {
     body: '#["messageVatObject",[{"methodName":"increment","presence":"%replaced:3"}]]',
     slots: []
   },
   result: 'p-76'
 }
 SYSCALL send ko30 { methargs: { body: '#["increment",[]]', slots: [] }, result: 'kp74' }
 SYSCALL subscribe v1 kp74
 SYSCALL vatstoreSet v1 idCounters {"exportID":20,"collectionID":7,"promiseID":21}
 DELIVERY { crankNum: 162n, vatID: 'v1', deliveryNum: 65n }
 DELIVERY.kd bringOutYourDead
 DELIVERY.vd bringOutYourDead
 DEQUEUE {
   type: 'send',
   target: 'ko30',
   msg: {
     methargs: { body: '#["increment",[]]', slots: [] },
     result: 'kp74'
   }
 }
 DELIVERY { crankNum: 163n, vatID: 'v6', deliveryNum: 20n }
 DELIVERY.kd message ko30 { methargs: { body: '#["increment",[]]', slots: [] }, result: 'kp74' }
 DELIVERY.vd message o+d11/1 { methargs: { body: '#["increment",[]]', slots: [] }, result: 'p-68' }
 SYSCALL resolve v6 [ [ 'kp74', false, { body: '#2', slots: [] } ] ]
 DELIVERY { crankNum: 165n, vatID: 'v6', deliveryNum: 21n }
 DELIVERY.kd bringOutYourDead
 DELIVERY.vd bringOutYourDead
 SYSCALL vatstoreSet v6 vom.o+d11/1 {"value":{"body":"#2","slots":[]}}
 DEQUEUE { type: 'notify', vatID: 'v1', kpid: 'kp74' }
 DELIVERY { crankNum: 166n, vatID: 'v1', deliveryNum: 66n }
 DELIVERY.kd notify [ [ 'kp74', { state: 'fulfilled', data: [Object] } ] ]
 DELIVERY.vd notify [ [ 'p+20', false, { body: '#2', slots: [] } ] ]
 SYSCALL resolve v1 [ [ 'kp73', false, { body: '#2', slots: [] } ] ]
 DELIVERY { crankNum: 167n, vatID: 'v1', deliveryNum: 67n }
 DELIVERY.kd bringOutYourDead
 DELIVERY.vd bringOutYourDead
-  ✔ non-durable exports are abandoned by upgrade of liveslots vat (9.8s)
+  ✔ non-durable exports are abandoned by upgrade of liveslots vat (9.5s)
   ─
 
   1 test passed
```

</details>

<details><summary>setup-style vat</summary>

```diff
diff --git 1/log.test-upgrade.non-liveslots.master.txt 2/log.test-upgrade.non-liveslots.pr.txt
index 9a2eb7969..43b893eba 100644
--- 1/log.test-upgrade.non-liveslots.master.txt
+++ 2/log.test-upgrade.non-liveslots.pr.txt
@@ -383,103 +383,85 @@ DELIVERY.vd bringOutYourDead
 DEQUEUE {
   type: 'upgrade-vat',
   vatID: 'v6',
   upgradeID: 'up1',
   bundleID: 'b1-1ce4dd057ae4e912700f4097f9a55f4dad6bb24be9adfb31460606947944c9179b346c5cd6dc7e877a751ec739935ca4d32065f26bc752c2e604af5726ec6ad8',
   vatParameters: { body: '#{"vatName":"exporter"}', slots: [] },
   upgradeMessage: 'vat exporter upgraded'
 }
 DELIVERY { crankNum: 60n, vatID: 'v6', deliveryNum: 10n }
 DELIVERY.kd stopVat {
   body: '#{"incarnationNumber":1,"name":"vatUpgraded","upgradeMessage":"vat exporter upgraded"}',
   slots: []
 }
 DELIVERY.vd stopVat {
   body: '#{"incarnationNumber":1,"name":"vatUpgraded","upgradeMessage":"vat exporter upgraded"}',
   slots: []
 }
 DELIVERY { crankNum: 60n, vatID: 'v6', deliveryNum: 11n }
 DELIVERY.kd startVat { body: '#{"vatName":"exporter"}', slots: [] }
 DELIVERY.vd startVat { body: '#{"vatName":"exporter"}', slots: [] }
 DEQUEUE {
   type: 'send',
   target: 'ko20',
   msg: {
     methargs: {
       body: '#["vatUpgradeCallback",["up1",true,"#undefined",2]]',
       slots: []
     },
     result: 'kp50'
   }
 }
 DELIVERY { crankNum: 62n, vatID: 'v2', deliveryNum: 8n }
 DELIVERY.kd message ko20 {
   methargs: {
     body: '#["vatUpgradeCallback",["up1",true,"#undefined",2]]',
     slots: []
   },
   result: 'kp50'
 }
 DELIVERY.vd message o+0 {
   methargs: {
     body: '#["vatUpgradeCallback",["up1",true,"#undefined",2]]',
     slots: []
   },
   result: 'p-63'
 }
 SYSCALL resolve v2 [ [ 'kp50', false, { body: '#"#undefined"', slots: [] } ] ]
 SYSCALL resolve v2 [ [ 'kp49', false, { body: '#{"incarnationNumber":2}', slots: [] } ] ]
 DELIVERY { crankNum: 63n, vatID: 'v2', deliveryNum: 9n }
 DELIVERY.kd bringOutYourDead
 DELIVERY.vd bringOutYourDead
 DEQUEUE {
   type: 'send',
   target: 'ko24',
   msg: {
     methargs: { body: '#["getDispatchLog",[]]', slots: [] },
     result: 'kp51'
   }
 }
 DELIVERY { crankNum: 65n, vatID: 'v7', deliveryNum: 6n }
 DELIVERY.kd message ko24 {
   methargs: { body: '#["getDispatchLog",[]]', slots: [] },
   result: 'kp51'
 }
 DELIVERY.vd message o+0 {
   methargs: { body: '#["getDispatchLog",[]]', slots: [] },
   result: 'p-60'
 }
 SYSCALL resolve v7 [
   [
     'kp51',
     false,
     {
       body: '#[["startVat",{"body":"!#{\\"vatName\\":\\"observer\\"}","slots":[]}],["bringOutYourDead"],["message","o+0",{"methargs":{"body":"!#[\\"acceptImports\\",[\\"$0.Alleged: Fake Remoteable exporter o+100\\"]]","slots":["o-50"]},"result":null}],["bringOutYourDead"],["message","o+0",{"methargs":{"body":"!#[\\"acceptWeakImports\\",[\\"$0.Alleged: Fake Remoteable exporter o+101\\"]]","slots":["o-51"]},"result":null}],["bringOutYourDead"],["message","o+0",{"methargs":{"body":"!#[\\"getDispatchLog\\",[]]","slots":[]},"result":"p-60"}]]',
       slots: []
     }
   ]
 ]
 DELIVERY { crankNum: 66n, vatID: 'v7', deliveryNum: 7n }
 DELIVERY.kd bringOutYourDead
 DELIVERY.vd bringOutYourDead
-  ✘ [fail]: non-durable exports are abandoned by upgrade of non-liveslots vat
+  ✔ non-durable exports are abandoned by upgrade of non-liveslots vat (9.9s)
   ─
 
-  non-durable exports are abandoned by upgrade of non-liveslots vat
-
-  test/upgrade/test-upgrade.js:612
-
-   611:   t.is(controller.kpStatus(upgradeKpid), 'fulfilled');
-   612:   t.is(kvStore.get(`${strongKref}.owner`), undefined);
-   613:   t.is(kvStore.get(`${weakKref}.owner`), undefined);  
-
-  Difference (- actual, + expected):
-
-  - 'v6'
-  + undefined
-
-  › file://test/upgrade/test-upgrade.js:612:5
-  › runMicrotasks (<anonymous>)
-
-  ─
-
-  1 test failed
+  1 test passed
```

</details>

**Comment by gibson042** [comment]
@warner The `kpResolution` changes and weaker assertions appear to have fixed this PR, and it is now ready for final review.

File: packages/SwingSet/test/upgrade/test-upgrade.js [hunk 4]
```diff
@@ -537,6 +546,95 @@ test('non-durable exports are abandoned by vat upgrade', async t => {
...
+    '1,1',
+    'strong observation of abandoned object retains ref counts',
+  );
+  // TODO: Expect and verify observer receipt of dispatch.retireExports
+  // and corresponding removal of weakKref ref counts.
+  // https://github.com/Agoric/agoric-sdk/issues/7212
+  t.is(
+    kvStore.get(`${weakKref}.refCount`),
+    '0,1',
+    'weak observation of abandoned object retains ref counts before #7212',
```
Comment (warner) [inline packages/SwingSet/test/upgrade/test-upgrade.js:628]: once this lands, please add a pointer to the file and line number in #7212, so we'll know which tests to update/check when we fix it

File: packages/SwingSet/test/vat-direct.js [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+    /** @type {VatOneResolution[]} */
+    let resolutions = promiseFulfillment(result, undefined);
+    try {
+      // Supported methods should have names that indicate what they
+      // cause this vat to do but (for greppability) should not
+      // duplicate names that appear in actual kernel/liveslots code.
+      switch (method) {
+        case 'getDispatchLog':
+          // Return a copy of dispatchLog so the original remains mutable.
+          resolutions = promiseFulfillment(result, dispatchLog.slice());
```
Comment (warner) [inline packages/SwingSet/test/vat-direct.js:75]: not worth changing anything, but be aware that the cool thing about setup-based test vats is that you can provide a `setup()` function that shares a lexical scope with your test code, do `t.is()` checks inside the delivery methods, record state directly into a shared closed-over array

that might simplify tests like this a bit, instead of needing to resolve a promise to the recorded data (and using `c.kpResolution` from your test case), you could just stash it somewhere. It's mostly useful if you want to ask about the vrefs that the vat is seeing: if you're interested in what the kref is, then yeah you kind of need to pass it through the dispatch/syscall boundary to let the c-list translator do it's thing

also, since you're using two vats and having one hold references into another, ok yeah you need to serialize something into a syscall.send or a resolve, and kmarshal is the easiest way to do that

File: packages/swingset-liveslots/src/stop-vat.js (hunk 3 above)
Comment (warner) [reply packages/swingset-liveslots/src/stop-vat.js:295]: My current thinking is that we punt on this until the future. I suspect we won't have a lot of virtual->durable or ephemeral->durable edges in the reference graph, and that userspace will only be using durables for things that really represent important long-term state. But sooner or later our GC story needs to improve, and a full mark-and-sweep scheme is probably in our future, at which point we'll be able to clean up the lingering durables that this fails to catch today.

**Review by warner — APPROVED** [review]
ok that looks good, thanks for diving into that test case

assuming you can figure out why CI is failing (maybe a server/service outage? maybe rebase and re-push, to re-trigger it?), feel free to land

maybe squash a bit first, defintely rebase first
