### PR TITLE
fix(SwingSet): Tolerate absence of a kpid from maybeFreeKrefs

### LINKED ISSUE #12138: Chain halt: `defineDurableKind` not called for tags [asyncFlow]
### **Summary**

Chain halted due to missing durable kind definition for tag `asyncFlow`.

---

### **Logs**

```
2025-10-20T14:10:41.161Z SwingSet: xsnap: v290: error during vat dispatch() of startVat,[object Object] (Error#1)
2025-10-20T14:10:41.162Z SwingSet: xsnap: v290: Error#1: defineDurableKind not called for tags: [asyncFlow]
...
2025-10-20T14:10:41.203Z SwingSet: controller: (Error#11)
Error#11: unfinished slog event cosmic-swingset-run-start ...
Error#12: storage lacks required key kp115870571.state
...
2:10PM ERR CONSENSUS FAILURE!!! err="Error: storage lacks required key (a string)"
```

---

### **Root Cause**

* Vat startup failed because `defineDurableKind` was not invoked for `asyncFlow`.
* `processRefCounts` failed because it was not prepared for kpids absent from the database because of rollback, leading to a kernel panic.

---

### **Fix**

**PR:** #12135
**Branch:** `dev-upgrade-22`

**Summary of Fix:**

* Prevents kernel panic when `processRefcounts` encounters an unknown kpid.
* Logs such occurrences to the console for diagnostics.

### PR DESCRIPTION
**Pull request by gibson042**
...on suspicion that its absence stems database rollback after a failed delivery

koid absence was already tolerated.

Fixes #12138

## Description
Rather than crash the kernel when `processRefcounts` encounters unknown krefs from `maybeFreeKrefs`, accumulate and log the information to the console and move on.

### Security Considerations
None known

### Scaling Considerations
n/a

### Documentation Considerations
TBD

### Testing Considerations
Verified manually; automated testing TBD.

### Upgrade Considerations
To be included in a minor bump of [agoric-upgrade-22a](https://github.com/Agoric/agoric-sdk/releases/tag/agoric-upgrade-22a). Also safe to hot patch outside of the formal upgrade process.

### CODE REVIEW

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 1]
```diff
@@ -1608,94 +1610,102 @@ export default function makeKernelKeeper(
...
+                  deleteKernelObject(kref);
+                }
               }
             }
           }
+        } catch (err) {
+          kdebug(`Ignoring lost object ${kref}`);
+          kvStore.set(
+            `${GC_ERRORS_KEY}.lostKrefs.${kref}`,
+            JSON.stringify({ crankNum, message, crankResults }),
```
Comment (michaelfig) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: IIUC, `JSON.stringify` of a record is deterministic (in order of property insertion), but typically avoided in kernel code in favour of tuples.  Should there be a comment here if this use is breaking with convention?

**Review by michaelfig — APPROVED** [review]
Looks straightforward, and amenable to a unit test after the emergency patch has been deployed.  Approving!

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 1 above)
Comment (dtribble) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: And is there any chance of bigints here? I think it chokes on bigints.

**Review by michaelfig — APPROVED** [review]
Again, LGTM!

**Review by mhofman — APPROVED** [review]
LGTM

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 1 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: Correct, and removed.
