### PR TITLE
fix(SwingSet): Make the README example work again

### LINKED ISSUE #12161: SwingSet demo does not run
working from this commit (latest on `master` as of writing) https://github.com/Agoric/agoric-sdk/tree/9bb987f67986eb98d04d64f5adedafc0f2d10271/packages/SwingSet

## Describe the bug
Following [instructions in README.md](https://github.com/Agoric/agoric-sdk/tree/9bb987f67986eb98d04d64f5adedafc0f2d10271/packages/SwingSet#swingset-vat)

## To Reproduce
```sh
yarn
yarn build
cd packages/SwingSet
yarn test
#   519 tests passed
#   1 known failure
bin/vat run demo/encouragementBot
# SES_UNHANDLED_REJECTION: (Error#1)
# Error#1: config.devices.0: need =1 of bundle/bundleSpec/sourceSpec/bundleName, got (an object)
```

## Expected behavior
Expected demo [instructions in README.md](https://github.com/Agoric/agoric-sdk/tree/9bb987f67986eb98d04d64f5adedafc0f2d10271/packages/SwingSet#swingset-vat) to work

## Platform Environment
 - what OS are you using?
 macOS on m-series
-what version of Node.js?
node v22.15.1
 - is there anything special/unusual about your platform?
m-series
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
> agoric-upgrade-16av-4574-g9bb987f679

## Context

error trace

```
❯ bin/vat run demo/encouragementBot
SES_UNHANDLED_REJECTION: (Error#1)
Error#1: config.devices.0: need =1 of bundle/bundleSpec/sourceSpec/bundleName, got (an object)

  at packages/SwingSet/src/controller/initializeSwingset.js:545:15
  at async Promise.all (index 0)
  at async processGroup (packages/SwingSet/src/controller/initializeSwingset.js:548:27)
  at async initializeSwingset (packages/SwingSet/src/controller/initializeSwingset.js:579:34)
  at async buildVatController (packages/SwingSet/src/controller/controller.js:671:23)
  at async main (packages/SwingSet/tools/vat.js:36:22)
```

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #12161

## Description
packages/SwingSet/tools/vat.js was calling buildVatController with invalid arguments, and that fact was suppressed by `@ts-expect-error`. This PR fixes that issue, and also issues related to demo/encouragementBot use of a loopbox device.

### CODE REVIEW

File: packages/SwingSet/tools/vat.js [hunk 1]
```diff
@@ -8,24 +8,39 @@ import util from 'util';
...
+
 function deepLog(item) {
   console.log(util.inspect(item, false, null, true));
 }
 
 async function main() {
-  const argv = process.argv.splice(2);
-  let withSES = true;
-  if (argv[0] === '--no-ses') {
-    withSES = false;
```
Comment (mhofman) [inline packages/SwingSet/tools/vat.js:19]: Wow this has been [gone a while](https://github.com/Agoric/agoric-sdk/pull/1234)!

File: packages/SwingSet/README.md [hunk 2]
```diff
@@ -53,7 +49,7 @@ In addition, a file named `bootstrap.js` must be present. This will contain
 the source for the "bootstrap Vat", which behaves like a regular Vat except:
 
 * At startup, its `bootstrap` method will be invoked, as `bootstrap(argv, vats)`
-* The `argv` value will be an array of strings, from the command line. So
+* The `argv` value will be an array of strings from the command line. So
```
Comment (mhofman) [inline packages/SwingSet/README.md:52]: I think this is the only remaining case of `argv` actually being an array, along with some tests. Someday we'll clean this up I guess.

File: packages/SwingSet/README.md [hunk 3]
```diff
@@ -69,18 +65,20 @@ anything else.
...
 non-local imports are allowed yet.
 
-The source file is expected to contain a single default export function named
-`setup`. This low-level function is invoked with a `syscall` object, and is
-expected to return a `dispatch` object.
+The source file is expected to export a `buildRootObject` function that returns
+a Vat "root object" managed by [Liveslots](../swingset-liveslots) with which
+other vats can interact, but it is also possible to bypass the "Live Slots"
+layer by exporting a default function named "setup" to be invoked with a
+`syscall` object and expected to return a `dispatch` object.
```
Comment (mhofman) [inline packages/SwingSet/README.md]: It's not simply the case of providing a different export. The vat has to be constructed with `enableSetup` option enabled to bypass liveslots.

The manager-factory will only warn about using a setup based vat if the manager type isn't local, but the different subprocess managers will actually fail if `enableSetup` is set. Local vats provide no availability protection (amongst other weirdness).

File: packages/SwingSet/README.md [hunk 4]
```diff
@@ -116,128 +114,72 @@ The system can pass-by-copy "Data Objects" with similar rules:
...
 
-## Sending Messages with Presences
+### Sending Messages with Presences
 
 When a Callable Object is sent to another Vat, it arrives as a Presence. This
 is a special (empty) object that represents the Callable Object, and can be
-used to send it messages.  If you are running SwingSet under SES (the default),
-then the so-called "wavy dot syntax" ([proposed for future ECMAScript](https://github.com/Agoric/proposal-wavy-dot))
-can be used to invoke eventual send methods.
+used to send it messages via the special `E()` wrapper.
```
Comment (mhofman) [inline packages/SwingSet/README.md]: Pedantically, it's through the `HandledPromise` static methods, for which `E` is only a helper.

File: packages/SwingSet/README.md [hunk 5]
```diff
@@ -116,128 +114,72 @@ The system can pass-by-copy "Data Objects" with similar rules:
...
+### Root Objects
 
 The "Root Object" is a callable object returned by `buildRootObject()`. It
 will be made available to the Bootstrap Vat.
 
-## Sending Messages with Presences
+### Sending Messages with Presences
 
 When a Callable Object is sent to another Vat, it arrives as a Presence. This
 is a special (empty) object that represents the Callable Object, and can be
```
Comment (mhofman) [inline packages/SwingSet/README.md]: Seems like we also need to go from `Callable` to `Remotable` ?

Also we may need to clarify that presences are themselves remotable, but they doesn't have local methods.

File: packages/SwingSet/README.md [hunk 6]
```diff
@@ -116,128 +114,72 @@ The system can pass-by-copy "Data Objects" with similar rules:
...
-method will be invoked (on some future turn) on whatever the Promise resolves
-to.
+Eventual-sends can target a not-yet-fulfilled Promise, deferring invocation of
+the method until the Promise fulfills to an object.
 
-If wavy dot syntax is used on a Promise which rejects, the method is not invoked, and
-the return promise's `rejection` function is called instead:
+If the target Promise rejects or fulfills to a non-object or object which does
+not support the method, the method is not invoked and the eventual-send promise
+is rejected.
```
Comment (mhofman) [inline packages/SwingSet/README.md]: the plain "object" terminology is bothering me. In particular, I don't believe we support a copy-record target which has a field that is a function.

I think we need to also use the remotable qualifier here to quality the kind of object.

File: packages/SwingSet/README.md [hunk 7]
```diff
@@ -116,128 +114,72 @@ The system can pass-by-copy "Data Objects" with similar rules:
...
 const badP = Promise.reject(Error());
-const p2 = badP~.foo();
+const p2 = E(badP).foo();
 p2.then(undefined, rej => console.log('rejected', rej));
 // prints 'rejected'
 ```
 
-If the Promise resolves to something which does not support the method,
-the method delivery will reject with a `TypeError`.
+### Promise Pipelining
```
Comment (mhofman) [inline packages/SwingSet/README.md:160]: We probably should say something about promise pipelining not being supported without `enablePipelining` manager option, which rules out all liveslots vats at the moment.

**Review by mhofman — COMMENTED** [review]
I skimmed the demo / tools changes, but didn't do a deep review.

Looks good overall, with some further tweaks suggested for the Readme.

File: packages/SwingSet/README.md (hunk 4 above)
Comment (gibson042) [reply packages/SwingSet/README.md]: Sure, but this is just moving text that already exists and doesn't need new pedantry.

**Comment by gibson042** [comment]
README updated again. Back to you, @mhofman.

**Review by mhofman — APPROVED** [review]
LGTM
