### PR TITLE
fix(SwingSet): Tolerate absence of a kpid from maybeFreeKrefs

### LINKED ISSUE #12138: Chain halt: `defineDurableKind` not called for tags [asyncFlow]
### **Summary**

Chain halted due to missing durable kind definition for tag `asyncFlow`.

---

### **Logs**

```
2025-10-20T14:10:41.161Z SwingSet: xsnap: v290: error during vat dispatch() of startVat,[object Object] (Error#1)
2025-10-20T14:10:41.162Z SwingSet: xsnap: v290: Error#1: defineDurableKind not called for tags: [asyncFlow]
...
2025-10-20T14:10:41.203Z SwingSet: controller: (Error#11)
Error#11: unfinished slog event cosmic-swingset-run-start ...
Error#12: storage lacks required key kp115870571.state
...
2:10PM ERR CONSENSUS FAILURE!!! err="Error: storage lacks required key (a string)"
```

---

### **Root Cause**

* Vat startup failed because `defineDurableKind` was not invoked for `asyncFlow`.
* `processRefCounts` failed because it was not prepared for kpids absent from the database because of rollback, leading to a kernel panic.

---

### **Fix**

**PR:** #12135
**Branch:** `dev-upgrade-22`

**Summary of Fix:**

* Prevents kernel panic when `processRefcounts` encounters an unknown kpid.
* Logs such occurrences to the console for diagnostics.

### PR DESCRIPTION
**Pull request by gibson042**
...on suspicion that its absence stems from database rollback after a failed delivery

koid absence was already tolerated.

Ref #12135
Fixes #12138

## Description
Rather than crash the kernel when `processRefcounts` encounters unknown krefs from `maybeFreeKrefs`, accumulate the krefs and log them to the console (except for GC messages like bringOutYourDead) and move on.

### Security Considerations
None known.

### Scaling Considerations
n/a

### Documentation Considerations
Covered by inline comments.

### Testing Considerations
Added unit test coverage.

### Upgrade Considerations
Similar changes are already on mainnet via #12135, and no further considerations apply here.

### CODE REVIEW

File: packages/SwingSet/tools/vat-puppet.js [hunk 1]
```diff
@@ -25,12 +28,46 @@ import { objectMap } from '@agoric/internal';
  * @typedef {Array<[name: string, ...args: unknown[]]>} CallLog
  */
 
+const PromiseWatcherI = M.interface('PromiseWatcher', {
+  onFulfilled: M.call(M.any()).returns(),
+  onRejected: M.call(M.any()).returns(),
+  getResult: M.call().returns(
+    M.or(['unsettled'], [M.or('fulfilled', 'rejected'), M.any()]),
```
Comment (mhofman) [inline packages/SwingSet/tools/vat-puppet.js:34]: Complete bikeshed. While `unsettled` is semantically correct, we rarely use that term for promises. The kernel code classifies the state these promises as `unresolved` which is only correct because the kernel is incapable of resolving a promise to another promise. The terminology I usually prefer is `pending`, which comes from the [Promises/A+ spec](https://promisesaplus.com/#promise-states)

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 2]
```diff
@@ -1640,6 +1645,9 @@ export default function makeKernelKeeper(
             // deleted). Message delivery should use that, but not us.
             const ownerKey = `${kref}.owner`;
             let ownerVatID = kvStore.get(ownerKey);
+            if (!ownerVatID) {
+              lostKrefs.push(kref);
+            }
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: So I was chatting with Brian, and not having a owner vatID is something that can normally happen when the exporting vat was terminated (including merely upgraded for non-durable exports I believe), but the object is still imported by other vats.

A lost kref should really be only when the kernel no longer knows about the kref at all. This might require a new call to get the state of the kref and its refcount.

File: packages/SwingSet/src/kernel/kernel.js [hunk 3]
```diff
@@ -1326,15 +1336,16 @@ export default function buildKernel(
...
       // processGCActionSet pruned some negated actions, but had no GC
       // action to perform. Record the DB changes in their own crank.
     } else if (message.type === 'cleanup-terminated-vat') {
       deliverP = processCleanupTerminatedVat(message);
-    } else if (gcMessages.includes(message.type)) {
-      deliverP = processGCMessage(message);
+    } else if (isGCType(message.type)) {
+      deliverP =
+        message.type === 'bringOutYourDead'
+          ? processBringOutYourDead(message)
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js]: If we left the explicit `else if` case for `bringOutYOuDead` above and use a proper type predicate, typescript is smart enough to know that the message isn't a `bringOutYourDead`, and we can avoid this ternary.

File: packages/SwingSet/src/kernel/kernel.js [hunk 4]
```diff
@@ -61,6 +61,16 @@ import { makeVatAdminHooks } from './vat-admin-hooks.js';
...
 
+/** @type {Set<RunQueueEvent['type']>} */
+const gcTypes = new Set([
+  'bringOutYourDead',
+  'dropExports',
+  'retireExports',
+  'retireImports',
+]);
+/** @type {(messageType: RunQueueEvent['type']) => boolean} */
+const isGCType = messageType => gcTypes.has(messageType);
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js]: I think we can make this better and use [type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates).

```suggestion
const gcTypes = /** @type {const} */([
  'bringOutYourDead',
  'dropExports',
  'retireExports',
  'retireImports',
]);

/**
 * @template T
 * @template {keyof T} K
 * @template {T[K]} V
 * @typedef {T extends { [key in K]: V } ? T : never} OneOfUnion
 */

/** @typedef {typeof gcTypes[number]} GcMessageType */
/** @typedef {OneOfUnion<RunQueueEvent, 'type', GcMessageType>} GcMessage */


/** @type {Set<RunQueueEvent['type']>} */
const gcTypesSet = new Set(gcTypes);

/** @type {(message: RunQueueEvent) => message is GcMessage} */
const isGCMessage = (message) => gcTypesSet.has(message.type);
```

Then we can use type narrowing and exhaustive checks in the different functions. [Playground](https://www.typescriptlang.org/play/?target=99&jsx=0&filetype=js#code/PQKhCgAIUgBAXApgWwA4BsCGTIGV0D28UMCAnqogCaIBmkA3gQEYBWiAxvAL6QDCmVABFsmEnFQAnApUnwyjAM7xJASwB2Ac17MCVBQEFIAKVwB5AHIA6ZWq2raCgvUzrIAUXUc9GzeNhSMohyCgz4RADaALq8ioTwiiTA4OCgENCQAGrY-JKI2KoEbq5UkACyrpiaKIjqxND+8pQ09AyQtr6QvABCAK7qVOiIAJJCjRTUdIyQrgo9-YOIAqjjzVNtbch6vUMAYgSSyNgAXJAA5LVUBABaqqjdmIqIAGwALGcANJCXN3cPT29Th0tF8frd7o8Xq9cAALTAAVgAjAAmIEqTq8XieK7g-5QvoDIZJFJpVaTVpnarwdwAD1QB3gZ0gAB9zupEMpqO4AG6YdC9bCIJmsi4DX4QgHveaExD7Q7YMktaabbZ7A5HeCnSmIal0hmfdoEXqSDiINF2TRfRRGk2ICqoAD85oxXUgAHEdbT6XICYtFetplsqDtZeqTmyOUgqDy+QKkAbrcbTc6QYak3bBE72uitK7eBZI1zefzBb6iRlyGtWoHVaH5ZrzkhlAaIjSgWRkLp0FFTgAlTgHKgAHgACtJZPIANKIMhffoAa3UBAA7uoAHx5yAAFUjZcQ-ur2PFeLee5Z7s9ep9CyG54LnOjxbjiDPrJ3yj30r90GSqTAB+mYFNFdbJ4FGAC2iA10yh1YJwIrJpyWVSBkFgyRRizGCkHQoRNzMVB4CwuCxgQiYlQYZYRHgTAhyAtdeFwZdfFwHVKNECCGHESBuJ43i+NQ+A4UkTRFFORjmNYwQqMwL5gGASBnEgCIBJhPQvkwYTFCiLi+N0ni8kUHYGyg1kFjoDRqHPdQdnQD4dL0njuF4GDFEUKp9x-El-1IqtkMQrUl3gBwyANXkwKEU5QNGL551QVQqBTYDMUgXt+gARV6RBMp5Wp4AsIhgog6Z-POJ4BgNajhJ1RKvmQRRNFOFy3OqLpeFS9QMqyxAcrqFiBiKtoSrODg8kFABaMLQuwUZIumoQ7IyBy+MTW1TjaZgbzNSAz14Vl1s2mbtoO3DuAWmAlt4sKRw0zABOCUS8CYrQWPgNjqLOi7eP0dRbtUDh8KCooHoXJdVy6ezdLa9LMuy7lcr4UakFAgbICG3pUE0SRMBoCbsCm8LZvCucMaxmhDqAj7Pu4jaZUOvdosgK6bruyQHvE57JOEURKap9HMexu0OWaraoOS9rOth3KAFUSYF5GfKQjZUYmLUODhLREFAgHCnURR8cOqL5oUgideB9RFxXNwxehrqete9Xqi1k2gZRoblA0+BQP1iKsjmr4maxlm2aezQXrezBN3FmHurh3rKs9hUFfI4qVfOKhxy9Bk9f9ubCYZ+c8loB6gOiSObcluohAzq8Eld1OzjyIK8kzuRs8Z3PfaJyAC7oYuc00UvrY66O7f7JvuprxIk4DQb68b1Q8mGNAs+9vOjZ7ovEsH10o9t2P4DHheRmX1u68oALEE0QUqDGzQODGzAuB172s0Nsvh733KCyvqM3T4Awn5FDPltM4zALRmF6PAAAmjaIQ+QqCr07qMd+EsY65W6OAyBMDjRwOxsA1WQxXDozGthZAGhr640ZDnAmSD5oQyWhtKgVJTgg0tigke+8+CEOsqgHchxyFRnlqQRCydd4VzygVRw54xFoN6pcaR5dZGvURprHIzJ6G6RkXbGW-MaCgQUR-cRfAHaqPgNrIGBjUF21wPHfR6jFoXS0fvKuMgW4JEsRw3Kh9m6Tw8Z-Oo3jj7encfY86jjFF22-tfP+ADAZuFZE49BmDoGwPgX4ox3D0Z8LIT9QRicwl6ShoYpRxJwDeF1vASAd8twTEUJAAAvJANIcBEKMHKcoXgIBgAAAoIhQHOGA3wECUk4PgZ8fpZx06uMnuM7iDcdRHzcdnCZ89F4nwSOMqIABKAA3F5dIwiUAYEFNuRoRysA4AYPOGcikty8EnGctAFzECMC3BEScMQsgQS3N8GkSABh1LaBEa5CgNCQA+ZFV0DptyQFOOyOGkheBmHZGYWgUt1A61Kc0ysitEKKWqbUiI1lOzBE+W6DgTV3I1MoJ5bFIj1jIsQKi9FOshyJLqF8M4iEDTkspdUaliB6LugpULdynl9ktImIwF6bKIn7wiFyiYZwohCq6WUoGlSCWUEUC9BpkB2TLjwDqbpWqOS7IlTixg3TUKuXcn2OVuUtkNI3Da4WkBVB1N5aK6onTkjtMqR6v+fKXmNOtd6xATr6kblNTqnUVg4SKDDba6oVhELmr-KQVAzNGDsp4ChcNnluK0H6IAtwQxNCqGYKodAqgABegtk2ICTcLJ1nFeIOEgM29yqapX1L7aVS4ZxW39N4v6lC9U9Wuu7XVTQezdJjuUjqVSVB1LCQADIevgFEPV5bK3VrrQ24WBhNLWvqlYFSGkRLmvnRqyABkjKTrPfe9AlToUzqsM+ypAUbJnDnXxRuxo3AAANYAABIGBTpTZVKkvAhxjUgOBlSehuDdPA5ejdHSnWnDAwwT93AgN-u4rwRA6AnjuvoF2qDvb+1nECsFIdjAR36R1IByAQG6OOG6WFQ6iHw1WG40IU63c4oJTgLxxtVhYrxW4FsgjTHiOkZeR2yjiAe00r7Y04aKjKEMbbXxOSkApA6iCsEMaqhNBLjyEx7iAHJDAZGvkJAlCEMQb4wJ3gMgEinHA6YSwNh+7BRU1Yb6v1-rO11ls3gAdbpoQej58w1ggKBcg6p6LQdItyd4gpsjymUtqZDTRvmpNEA6eHbpAzRn4AmckGZizBwPL-pY3ZtjRWBbOfE8Lfjc1eCtbJj7Dr3besjEE+3eA11A6xe8wwXziWAucby2l2LGXCOuhIzlijeXWkafOGrVwjtsDmN1rp6zTT5KVeq7VyzDXeK2fsyYp2cS6kDZTe542j2pszf8xaZLfHPOm2W-J74inyOdpO5t6jmnBlaGGdgyQuCEEsnsfxPjW2aPuzkF7JjZXGvwFY0B57qnEK8AJ118K+GVvZaUxRwNfBg0qa2dj3iBmDDoHQO6Pg+bG11KIDCYIqN1aQCh5oGHqTsbuq8PyGgMxIA1uUApegG9FBWBO2OxXk6+OK-PYIbpIaNwgfA4gfDWyrCsAIBobpTIh0re4hVxuF3zNXZO7dtjJOicuYW91lzivyeA7Wy8vTN2mvAdYWDFLysaWu4mD7rL-TuApBt95bi6Qk+QCEB6rN8A1YKXZJAGgNaEUKEQPvKwHh94ClZ7OfnHrIBMVZ4Ll5HA+RDFKGCsQPEYAACI8+qAL5AEarh5wd8gLQA40u4H5+CGQO26laDYX5y8xQatqAhkkH31SBAnh1LbynsKNfVCCWl0udQY0jnyFG2Z9QqBIFjQAI7R3UgMGvQo68W0NYJF50GdSjZHTATAvOxeKRBSoQl5yj6orhfCCTV7V6N6s6WQj6r75BZ6SD9C37RzfD7xWgEA-4DrlS54EAchgGVJkBf6v414wh-QwijZ7517MBKbqDcgEDoBwylDdIdqzDG4-7YEBDZoMC5q8ApZcG3aApjgEBkJPBDgIwD79iGQvqKD0Q-7JDcSPBkBeDD4lpxK54kY97BC5r06MZM7yRwIOb0BF6T6QG5hgrv6c7CxzgDB85WGPCGRoAaGCQ5BbBy7OBMYGZWFAEvLLhCh5CaET4WiowEDS676j6uCKD+EhFWGfqGbSBiHXanZ74H6uDfCSDSCSAl7DD0D+F76P7oyQB35dSdD77Z7S6BBJFfD+FnCs5eHyR5AX4OaoR1DoFmHkG5jv55DK4GGQCk7ILV5GZlSVJFAzB165p1KIA0imgEQ4EII1HkFZ5Uh1L74NHD6JF3pGhIB9SPi5Ql52zl7oCV6mGSAKDj7aFnF2zUFs5whwwzDrGKCUAcAOB-SjbIIlBV51K15s60EJEEDcjxSWSPAzDFDCS9CtH1A8RDCVICYra5Yo5SoACEaOg6jOPEAm6uEmcJ8mTGMJQRlxI4eqFgZgAA+kIO4GusMJkO4L2FAqSXwL2AYBYJOKSb2O4LgFLGuluLgCtgZluLzn3qIVsMUKWu0KpDsKUH8d3gip0KYXUHUvAGEVYWFCXgYOoAoIXMELUKaFPDxAZpYYKfKe4ooBKegKUEuDLkUNUKvn8VYdcnZiRmcHUgZPSLrHujWmfp8e-usYXN4P0CaWaVKS8jQC0blNQExgiRJqjppmVAguidxGOtIJAiGlsSmbsXbPTtbiDt0kicmUgAmfqfJMGk-m0U8RcidtxKGXkJCRmfvP2LQHwEaHUFmSdpTvoXpJiY0vmalnNNmdxMpgJoWV9JwDWblHWV4nQE2QGa2RdDKcEESY0oELqbGgMFxn7GmUgKmpejqLVHxjOteoUkDmRgHnpAZiWdXnkCUZlKUJ8e7GQIqYKQ6eyOgM6XehyG6YoB6fvpXlcIQZWUWZoWGW0X6c2e4oadAZCABdxM+SRtOIgLIFYNjFQMGluAQCIUkagt0j2duVVPAHuRJgef2eDJDCdgZpiT8fXpAGZLQBZKUPAe0McqMavleffseS8hEfQPOZkWQL7sDlGZ1jGWyJIiFIWdWTUHUPlEFI4KPFOWBbOXxNxYuf8SuVJT9o2oeURuxTmeDupjRg5uNJNIWQZgZUFLmBHAarnioaFlQZRaoMgKhFQKoIKMcXgdmB7JQidkpXqsuULAjI5qYgpVpX7jpYiXpbGbYnjGJVoQispb5a5DYh7KBEFatvxRtmFQVppkNqVh2SOcEXFdICuTosVslSlppaletp2rpZlTtvdgduFnrNFflT5YVX5XVWYg1Sle2QJd2kJaAskrDvDsdrpN5Uua1a5BgkMlgqLlQF1dpT1VRuFRGD-NQLfPfI-HEsNfpmduNYoDEqWrqlIP0JZNaKhPqpfNfDMKWooF8BtJUnCBaWEX-GRfJBtTrKEYZsEPAcgCXv2N4JIKUFYUIN0GvntgQYaYgAvApGDP3ubL0Y5PNeldGRDjtpkqgCQsEDkhQkZblTxKNSpX5WjdkgItQKVeGuVd1dTntbTuGvTk1YSS1QQCuUGrTWVRTtpaedxLsJgNWkBv0JgMwLeEqQTa5NYb1VKpHpQNHo5OsZAVvugMuJgA+e+bjnZlvrkFIRyEZDde0W4B2vvm+awL0MoOsSSeSZSdSbSfSYycyayeyZydybgExkmVrbIXqpgIreUUpSts7p+ooH+nHkAA)

File: packages/SwingSet/src/kernel/kernel.js [hunk 5]
```diff
@@ -1153,14 +1163,16 @@ export default function buildKernel(
...
       message.type === 'startVat'
     ) {
       return `${message.type} ${message.vatID}`;
+    } else if (isGCType(message.type)) {
+      // All GC messages other than bringOutYourDead include a list of krefs.
+      const krefs = message.krefs.map(e => `@${e}`).join(' ');
+      // prettier-ignore
+      return `${message.type} ${message.vatID} ${krefs}`;
     } else {
       return `unknown message type ${message.type}`;
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js]: FYI my type predicate experiment shows we actually have 2 unhandled types: `"negated-gc-action" | "cleanup-terminated-vat"`

File: packages/SwingSet/tools/vat-puppet.js [hunk 6]
```diff
@@ -192,14 +195,26 @@ export const makeReflectionMethods = (vatPowers, baggage, vatParameters) => {
...
+    if (typeof arg !== 'symbol' || !Symbol.keyFor(arg)) return arg;
+    if (!arg.description?.match(decimalIntPatt)) return arg;
+    return results.at(Number(arg.description));
+  };
   for (const [methodName, ...args] of initialCalls) {
-    await rootObject[methodName](...args);
+    const translatedArgs = args.map(translateArg);
+    const result = rootObject[methodName](...translatedArgs);
+    results.push(result);
   }
```
Comment (mhofman) [inline packages/SwingSet/tools/vat-puppet.js:219]: Oh look another bespoke "invoke multiple" mechanism. I think writing one should become an interview question.

File: packages/SwingSet/test/upgrade/upgrade.test.js [hunk 7]
```diff
@@ -836,91 +838,100 @@ test('failed upgrade - lost promise export', async t => {
...
+      const expectCall = expectSpyCalls[i];
+      const [expectMethodName, ...expectArgs] = expectCall;
+      const [actualMethodName, ...actualArgs] = actualSpyCalls[i] || [];
+      if (actualMethodName !== expectMethodName) {
+        expectation.push(expectCall);
+        continue;
+      }
+      const updatedExpectArgs = expectArgs.map((arg, i) =>
+        isPromise(arg) && isPromise(actualArgs[i]) ? actualArgs[i] : arg,
+      );
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade/upgrade.test.js]: I'm not sure I understand why we're doing this. This is effectively saying any promise in the right position will work, right, even if the 2 promises are unrelated (because we can't test promise identity?).

I would kinda prefer using an explicit sentinel value, maybe a unique symbol?

File: packages/SwingSet/test/upgrade/upgrade.test.js [hunk 8]
```diff
@@ -836,91 +838,100 @@ test('failed upgrade - lost promise export', async t => {
...
-        ['watchSettledPromiseByProxy', 'v1', bootstrapSpy],
+        ['makeSettledPromise', 'v1'],
+        ['sendOnly', spy, 'log', 'v1', Symbol.for(-1)],
+        ['watchSettledPromiseByProxy', 'v1', spy],
       ],
     },
   });
   await assertSpyCalls('started v1', [
-    ['log', 'v1'],
+    ['log', 'v1', Promise.resolve('v1')],
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade/upgrade.test.js]: Yeah I'm fearing this is giving a false sense that `assertSpyCalls` will actually check that the 3rd argument is a promise resolved to `v1`.

**Review by mhofman — COMMENTED** [review]
Besides some nits, this is looking good so far.

I am however a little suspicious about false positives in the koid case. I think we should try to filter our orphaned objects from missing objects.

File: packages/SwingSet/tools/vat-puppet.js (hunk 1 above)
Comment (gibson042) [reply packages/SwingSet/tools/vat-puppet.js:34]: I'll stick with the precise semantics here.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 2 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: https://github.com/Agoric/agoric-sdk/pull/12145/commits/fe7b5430b248da7d0588def54d297ed151715b78

File: packages/SwingSet/src/kernel/kernel.js (hunk 3 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/kernel.js]: Restored.

File: packages/SwingSet/src/kernel/kernel.js (hunk 4 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/kernel.js]: Good idea. https://github.com/Agoric/agoric-sdk/pull/12145/commits/f8ca2d4b808fde7b47cc13e2300675561d0930e5?w=1

File: packages/SwingSet/src/kernel/kernel.js (hunk 5 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/kernel.js]: Fixed.

File: packages/SwingSet/tools/vat-puppet.js (hunk 6 above)
Comment (gibson042) [reply packages/SwingSet/tools/vat-puppet.js:219]: Yeah. I strongly considered just accepting a string for Compartment evaluation, and could still be persuaded into that position. `initialCalls: Array<[methodName: string, ...args: (ResultReference | Passable)[]]>` is _right_ on the edge for me.

File: packages/SwingSet/test/upgrade/upgrade.test.js (hunk 8 above)
Comment (gibson042) [reply packages/SwingSet/test/upgrade/upgrade.test.js]: Updated to actually compare state and settlement values: https://github.com/Agoric/agoric-sdk/pull/12145/commits/4bc513fb60df59ebc8c348f2a9094aa089f5b3a4 https://github.com/Agoric/agoric-sdk/pull/12145/commits/78f80395671c74a26b9683120302ef2c0ee5e8ef

File: packages/SwingSet/src/kernel/kernel.js [hunk 9]
```diff
@@ -61,15 +61,21 @@ import { makeVatAdminHooks } from './vat-admin-hooks.js';
...
+const gcMessageTypes = /** @type {const} */ ([
   'bringOutYourDead',
   'dropExports',
   'retireExports',
   'retireImports',
 ]);
-/** @type {(messageType: RunQueueEvent['type']) => boolean} */
-const isGCType = messageType => gcTypes.has(messageType);
+
+/** @typedef {Extract<RunQueueEvent, { type: GcMessageType }>} GcMessage */
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js:73]: Oh yeah that's much better! Why couldn't I remember the `Extract` trick!

File: packages/SwingSet/src/kernel/kernel.js [hunk 10]
```diff
@@ -1147,34 +1153,40 @@ export default function buildKernel(
...
+      case 'changeVatOptions':
+        // prettier-ignore
+        return `changeVatOptions ${message.vatID} options: ${JSON.stringify(message.options)}`;
+      case 'startVat':
+      case 'bringOutYourDead':
+        return `${message.type} ${message.vatID}`;
+      default:
+        if (isGcMessage(message)) {
+          // @ts-expect-error re-narrowing `message`
+          assert(message.type !== 'bringOutYourDead');
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js]: Why do we need this?

File: packages/SwingSet/src/kernel/kernel.js [hunk 11]
```diff
@@ -1336,17 +1348,17 @@ export default function buildKernel(
...
-      deliverP =
-        message.type === 'bringOutYourDead'
-          ? processBringOutYourDead(message)
-          : processGCMessage(message);
+    } else if (message.type === 'bringOutYourDead') {
+      deliverP = processBringOutYourDead(message);
+    } else if (isGcMessage(message)) {
+      deliverP = processGCMessage(message);
     } else {
+      // @ts-expect-error unreachable
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js:1379]: 🎉

File: packages/SwingSet/src/kernel/kernel.js [hunk 12]
```diff
@@ -1120,32 +1153,42 @@ export default function buildKernel(
...
+      case 'bringOutYourDead':
+        return `${message.type} ${message.vatID}`;
+      default:
+        if (isGcMessage(message)) {
+          // @ts-expect-error re-narrowing `message`
+          assert(message.type !== 'bringOutYourDead');
+          const krefs = message.krefs.map(e => `@${e}`).join(' ');
+          return `${message.type} ${message.vatID} ${krefs}`;
+        }
+        return `unknown message type ${message.type}`;
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js:1207]: Surprised we don't need an unreachable `ts-expect-error` here now...

**Review by mhofman — APPROVED** [review]
Fantastic!

File: packages/SwingSet/src/kernel/kernel.js (hunk 10 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/kernel.js]: Seems like it was because the `message` parameter wasn't typed. Adding that removes the need for this and makes the unreachability of the `Fail` discoverable.
