### PR TITLE
fix(ymax-planner): Run with 6-second heartbeats

### LINKED ISSUE #12126: Planner hangs after network disconnect
### Description
When the network disconnects (e.g., Wi‑Fi off) while the planner is running, it stops processing blocks and never recovers after connectivity is restored. The process stays alive but the event loop is stuck, producing no further output.

### Impact
- Planner can silently stall indefinitely after transient network issues.
- Operational reliability is compromised; manual restart required.

### Steps to Reproduce
1. Start the planner locally; observe periodic logs like `{ blockHeight: N, portfolioEvents: [], pendingTxEvents: [] }`.
2. Disable Wi‑Fi (or otherwise cut network).
3. Re-enable Wi‑Fi.
4. Observe that no new block logs appear and the planner remains stuck.

### Expected behavior
- Planner detects the dead connection and either reconnects or exits so a supervisor can restart it. Processing should resume after network returns.

### Actual behavior
- The planner’s subscription loop hangs indefinitely; no errors or reconnection attempts; no further logs. Not good for production.

### Root cause
- The WebSocket subscription generator in `CosmosRPCClient.subscribeAll` waits on an internal promise that is only resolved by incoming messages. When the socket closes or the network drops, no further messages arrive and the generator neither throws nor completes. The engine’s `for await` loop thus blocks forever.

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #12126

## Description
Run ymax-planner with 6-second heartbeats (via websocket ping/pong frames), crashing the process for restart by supervisor when a ping doesn't get a pong response in time.
* fix(ymax-planner): Finalize CosmosRPCClient subscriptions upon websocket close/error
* feat(ymax-planner): Add heartbeat logic to CosmosRPCClient
  _Note that this locks us in to the "ws" packages, because the WHATWG WebSocket API does not expose ping/pong frames._
* fix(ymax-planner): Run with 6-second heartbeats

### Security Considerations
None known

### Scaling Considerations
Any downtime incurs catchup proportional to its duration. This is more significant for resolver functionality than for planner functionality, but both are able to recover.

### Documentation Considerations
n/a

### Testing Considerations
Tested manually.

### Upgrade Considerations
Safe to deploy immediately.

### CODE REVIEW

**Review by dckc — APPROVED** [review]
It's worth a try. I think I understand the design.

That's the basis of my approval; not that I'm prepared to maintain this code. So you may want to stand by for a review from somebody who understands the code better.

File: services/ymax-planner/src/cosmos-rpc.ts [hunk 1]
```diff
@@ -47,21 +61,50 @@ export class CosmosRPCClient extends JSONRPCClient {
...
       this.#openedPK.reject(err);
       this.#closedPK.reject(err);
+      for (const sub of this.#subscriptions.values()) {
+        sub.fail(err);
+      }
+      this.#subscriptions.clear();
     });
+    if (heartbeats) {
+      let closed = false;
+      void this.#closedPK.promise.catch(sink).then(() => {
```
Comment (dtribble) [inline services/ymax-planner/src/cosmos-rpc.ts:85]: very minor: `this.closed().catch...`?

**Review by dtribble — APPROVED** [review]
LGTM
