### PR TITLE
fix: address account sequence errors when resolving transactions

### LINKED ISSUE #11958: ymax-planner: resolver shows `account sequence mismatch` error when resolving multiple transactions at once
I started the resolver, and it attempted to resolve `CCTP_TO_NOBLE` transactions.

Currently, these transactions rely on a very fragile check - it only verifies if there’s a balance increase. If the Noble ICA balance is greater than the amount sent to the wallet, it assumes the transaction succeeded and tries to resolve it.

Because of this, it tried to resolve multiple pending `CCTP_TO_NOBLE` transactions at once, which resulted in the following error:
```
Error#62: Broadcasting transaction failed with code 32 (codespace: sdk). Log: account sequence mismatch, expected 538, got 537: incorrect account sequence
  at async Object.executeOffer (packages/client-utils/dist/signing-smart-wallet-kit.js:35:9)
  at async resolvePendingTx (file:///home/rabi/Desktop/Agoric/agoric-sdk/services/ymax-planner/src/resolver.ts:52:18)
  at async Object.watch (file:///home/rabi/Desktop/Agoric/agoric-sdk/services/ymax-planner/src/pending-tx-manager.ts:171:5)
  at async handlePendingTx (file:///home/rabi/Desktop/Agoric/agoric-sdk/services/ymax-planner/src/pending-tx-manager.ts:216:5)

 Failed to process pending tx tx30 with lookback {
  blockHeight: 3103710n,
  tx: {
    txId: 'tx30',
    amount: 50000n,
    destinationAddress: 'cosmos:grand-1:noble1gpqqdhkxwuu0rfnp592xelse3hv0uks4gajupgupwk93phcfy0xqskn7xw',
    status: 'pending',
    type: 'CCTP_TO_NOBLE'
  }
} (Error#63)
Error#63: Broadcasting transaction failed with code 32 (codespace: sdk). Log: account sequence mismatch, expected 538, got 537: incorrect account sequence
  at async Object.executeOffer (packages/client-utils/dist/signing-smart-wallet-kit.js:35:9)
  at async resolvePendingTx (file:///home/rabi/Desktop/Agoric/agoric-sdk/services/ymax-planner/src/resolver.ts:52:18)
  at async Object.watch (file:///home/rabi/Desktop/Agoric/agoric-sdk/services/ymax-planner/src/pending-tx-manager.ts:171:5)
  at async handlePendingTx (file:///home/rabi/Desktop/Agoric/agoric-sdk/services/ymax-planner/src/pending-tx-manager.ts:216:5)

 Failed to process pending tx tx36 with lookback {
  blockHeight: 3104292n,
  tx: {
    txId: 'tx36',
    amount: 500000n,
    destinationAddress: 'cosmos:grand-1:noble1jx8m235686w20uq8fftdp3ue2a45mjv6ekrvq2plqqk5fqak5r9s5eg72g',
    status: 'pending',
    type: 'CCTP_TO_NOBLE'
  }
} (Error#64)
```

This was expected because we multiple transactions were being resolved simultaneously.

### PR DESCRIPTION
**Pull request by rabi-siddique**
closes: #11958 

## Description

- Created a `SequenceManager` that handles account sequence numbers and syncs with network state for error recovery.
- Created a `SmartWalletWithSequence` wrapper that provides queued transaction execution to prevent sequence conflicts.

### Scaling Considerations

- Transactions are queued and processed sequentially to prevent sequence conflicts, which may limit throughput under
   high concurrent load
- The operation queue in `SmartWalletWithSequence` could grow unbounded under sustained failures (noted as TODO for now)
  
### Testing Considerations

New tests have been added to verify the changes introduced in this PR.

### Upgrade Considerations

The changes introduced in this PR extend existing APIs without breaking current functionality.

### CODE REVIEW

File: packages/client-utils/src/signing-smart-wallet-kit.ts [hunk 1]
```diff
@@ -50,39 +55,79 @@ export const makeSigningSmartWalletKit = async (
...
+  const executeOffer = async (offer: OfferSpec, data?: SignerData) => {
     const before = await client.getBlock();
 
-    await sendBridgeAction(
-      harden({
-        method: 'executeOffer',
-        offer,
-      }),
-    );
+    if (data) {
```
Comment (dckc) [inline packages/client-utils/src/signing-smart-wallet-kit.ts]: is this `if` statement needed? if `data === undefined` then passing it has the same effect as not passing it, right?

File: packages/client-utils/src/signing-smart-wallet-kit.ts [hunk 2]
```diff
@@ -50,39 +55,79 @@ export const makeSigningSmartWalletKit = async (
...
-      harden({
-        method: 'invokeEntry',
-        message,
-      }),
-    );
+  const invokeEntry = async (
+    message: InvokeEntryMessage,
+    data?: SignerData,
+  ) => {
+    const transaction = data
```
Comment (dckc) [inline packages/client-utils/src/signing-smart-wallet-kit.ts]: again, can't we just pass `data` straight thru in both cases?

File: services/ymax-planner/src/sequence-manager.ts [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+  address: string;
+  chainKey: string;
+};
+
+type SequenceManagerPowers = {
+  cosmosRest: CosmosRestClient;
+  log?: (...args: unknown[]) => void;
+};
+
+export class SequenceManager {
```
Comment (dckc) [inline services/ymax-planner/src/sequence-manager.ts]: I don't have much experience with JS classes. I defer to @gibson042

File: services/ymax-planner/src/sequence-manager.ts [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+  private readonly chainName: string;
+
+  private initialized = false;
+  private readonly log: (...args: unknown[]) => void;
+
+  constructor(io: SequenceManagerPowers, config: SequenceManagerConfig) {
+    this.address = config.address;
+    this.chainName = config.chainKey;
+    this.cosmosRest = io.cosmosRest;
+    this.log = io.log ?? (() => {});
```
Comment (dckc) [inline services/ymax-planner/src/sequence-manager.ts]: IIUC, `this.log` is not encapsulated and it's mutable. So I'd have to check all the code in the process to know whether it gets clobbered. Likewise all the other properties and methods, I suppose.

**Review by dckc — COMMENTED** [review]
some very minor comments

**Comment by rabi-siddique** [comment]
Looking at the logs:
```
  [SmartWalletWithSequence]: Creating SignerData with sequence: 597, accountNumber: 377
  [SmartWalletWithSequence]: Creating SignerData with sequence: 598, accountNumber: 377
  [SmartWalletWithSequence]: Creating SignerData with sequence: 599, accountNumber: 377
  [SmartWalletWithSequence]: Creating SignerData with sequence: 600, accountNumber: 377
  [SmartWalletWithSequence]: Creating SignerData with sequence: 601, accountNumber: 377
 ```
 
Multiple transactions are running concurrently and each is consuming sequence numbers from the local counter. But when they hit the network, they discover the actual sequence is still `598`, causing all subsequent transactions to fail.

```
  [SmartWalletWithSequence]: Sequence error detected in executeOffer, syncing and retrying: Broadcasting transaction failed with code 32
  (codespace: sdk). Log: account sequence mismatch, expected 598, got 599: incorrect account sequence
  [SmartWalletWithSequence]: Creating SignerData with sequence: 597, accountNumber: 377
  [SmartWalletWithSequence]: Retry failed for executeOffer: Broadcasting transaction failed with code 32 (codespace: sdk). Log: account
  sequence mismatch, expected 599, got 597: incorrect account sequence
```

Concurrent execution without proper sequence coordination. The sequence manager tracks sequence numbers locally but multiple pending transactions execute in parallel, each grabbing the next sequence number before any complete.

**Comment by rabi-siddique** [comment]
I did some e2e testing and the transactions are now being queued successfully, and there are no account sequence mismatch errors. But, when the first transaction is processed, it seems to get stuck in an infinite loop. The only log I see from the wallet is:

```
2025-09-23T11:30:32.714571620Z offer not in wallet at block 3324050 retrying...

```

File: services/ymax-planner/src/engine.ts [hunk 5]
```diff
@@ -246,6 +247,7 @@ export const processPendingTxEvents = async (
       const streamCell = parseStreamCell(cellJson, path);
       const value = parseStreamCellValue(streamCell, -1, path);
       data = marshaller.fromCapData(value);
+      if (data?.status !== TxStatus.PENDING) continue;
       mustMatch(data, PublishedTxShape, `${path} index -1`);
       const tx = { txId, ...data } as PendingTx;
       log('New pending tx', tx);
```
Comment (dckc) [inline services/ymax-planner/src/engine.ts:518]: The next couple lines are:

```ts
      // Tx resolution is non-blocking.
      void handlePendingTxFn(tx, txPowers).catch(err => error(errLabel, err));
```

I can imagine that makes this PR challenging.

File: services/ymax-planner/src/sequence-manager.ts [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+  }
+
+  private ensureInitialized(): void {
+    if (!this.initialized) {
+      Fail`SequenceManager not initialized. Call initialize() first.`;
```
Comment (dckc) [inline services/ymax-planner/src/sequence-manager.ts]: Rather than having the possibility of a constructed but not initialized object, I suggest using a static factory method: a static method to `fetchAccountInfo` and pass the results to the constructor.

File: services/ymax-planner/src/sequence-manager.ts [hunk 7]
```diff
@@ -0,0 +1,112 @@
...
+      `Synced sequence: ${oldSequence} → ${this.sequence} (network: ${accountInfo.sequence})`,
+    );
+  }
+
+  private async fetchAccountInfo(): Promise<AccountInfo> {
+    try {
+      const response = (await this.cosmosRest.getAccountSequence(
+        this.chainName,
+        this.address,
+      )) as AccountResponse;
```
Comment (dckc) [inline services/ymax-planner/src/sequence-manager.ts]: why this cast? doesn't `getAccountSequence` have a useful return type?

File: services/ymax-planner/src/sequence-manager.ts (hunk 3 above)
Comment (mhofman) [reply services/ymax-planner/src/sequence-manager.ts]: FYI `private` is smoke from TS that doesn't actually create private fields. Why not use actual JS private fields, aka `#foo` ?

Using a class is "ok" if we maintain proper encapsulation.

File: packages/client-utils/src/signing-smart-wallet-kit.ts [hunk 8]
```diff
@@ -50,38 +55,72 @@ export const makeSigningSmartWalletKit = async (
...
+
+    const txBytes = TxRaw.encode(signedTx).finish();
+    return client.broadcastTx(txBytes);
   };
 
-  const executeOffer = async (offer: OfferSpec) => {
+  const executeOffer = async (
+    offer: OfferSpec,
+    data?: SignerData,
+    pollForResult = true,
```
Comment (turadg) [inline packages/client-utils/src/signing-smart-wallet-kit.ts]: It's a smell for the return type to depend on the arguments.

if you don't want to poll for result why bother with this function?

```
    await sendBridgeAction(
      harden({
        method: 'executeOffer',
        offer,
        defaultFee,
        data,
      }),
    );
```

File: services/ymax-planner/src/sequence-manager.ts (hunk 3 above)
Comment (gibson042) [reply services/ymax-planner/src/sequence-manager.ts]: > Using a class is "ok" if we maintain proper encapsulation.

Note that this means using actual JS `#foo` private fields and not TS `private foo`.

File: packages/client-utils/src/signing-smart-wallet-kit.ts (hunk 8 above)
Comment (turadg) [reply packages/client-utils/src/signing-smart-wallet-kit.ts]: PTAL https://github.com/Agoric/agoric-sdk/pull/11986

**Comment by dckc** [comment]
> Extended signing-smart-wallet-kit.ts to accept SignerData for manual sequence control

that change moved to another PR, right? I see no changes outside of `services/ymax-planner`

File: packages/client-utils/src/smart-wallet-with-sequence.ts [hunk 9]
```diff
@@ -0,0 +1,209 @@
...
+          isProcessingQueue = false;
+        });
+      }
+    });
+  };
+
+  /**
+   * Send a bridge action with managed sequence number
+   */
+  const sendBridgeAction = async (
```
Comment (dckc) [inline packages/client-utils/src/smart-wallet-with-sequence.ts]: what post-condition guarantees does this method provide? does it guarantee that the tx is in a block, for example?

Comment (rabi-siddique) [reply packages/client-utils/src/smart-wallet-with-sequence.ts]: The `sendBridgeAction` method returns `Promise<DeliverTxResponse>` (from CosmJS)

I think `DeliverTxResponse` is only returned after the transaction has been delivered and included in a block. Will need to verify that though

Comment (michaelfig) [reply packages/client-utils/src/smart-wallet-with-sequence.ts]: `Promise<DeliverTxResponse>` fulfils as soon as the transaction enters the mempool on the RPC node you've connected to.  That can still be significantly sooner than when (if ever) it is included in a block.  The only ways to discover its block inclusion are to poll or create a websocket query for the txhash.

**Comment by gibson042** [comment]
Before reviewing in earnest, I would like to express my strongly-held position that any transaction queueing code belongs in client-utils, even if it's marked `@alpha`. For an analogous example, see [`reflectWalletStore`](https://github.com/Agoric/agoric-sdk/blob/a62e38f05bf0b676c708b7861b88b2b70b841469/packages/client-utils/src/signing-smart-wallet-kit.ts#L170) and use thereof.

File: packages/client-utils/src/sequence-manager.ts [hunk 10]
```diff
@@ -0,0 +1,103 @@
...
+    '@type': string;
+    key: string;
+  };
+  account_number: string;
+  sequence: string;
+};
+
+export type AccountResponse = {
+  account: AccountInfo;
+};
```
Comment (gibson042) [inline packages/client-utils/src/sequence-manager.ts]: These types (or at least their analogs) already exist in both packages/client-utils/dist/codegen and packages/cosmic-proto, and should not be recreated here.

File: packages/client-utils/src/sequence-manager.ts [hunk 11]
```diff
@@ -0,0 +1,103 @@
...
+      `Synced sequence: ${oldSequence} → ${sequence} (network: ${acctInfo.sequence})`,
+    );
+  };
+
+  return harden({
+    getSequence,
+    getAccountNumber,
+    syncSequence,
+  });
+};
```
Comment (gibson042) [inline packages/client-utils/src/sequence-manager.ts:62]: Given that the output from `makeSequenceManager` is constrained to a single address, giving it a `fetchAccountInfo` that can query for arbitrary addresses is too much authority (and requiring that it return a `{ account: { "@type": "…", … } }` object is too constraining for convenient use with e.g. JSON-RPC clients). Suggested refactoring:

<details>

```suggestion
/**
 * Manage sequence numbers for submitting transactions from a single address.
 *
 * @alpha
 */
export const makeTxSequencer = async (
  fetchAccount: () => Promise<BaseAccount>,
  { log = () => {} }: { log?: (...args: unknown[]) => void },
): Promise<TxSequencer> => {
  const initial = await fetchAccount();
  const accountNumber: bigint = initial.accountNumber;
  let sequenceNumber: bigint = initial.sequence;
  log(
    `Initialized accountNumber ${accountNumber} sequence number to ${sequenceNumber}`,
  );

  /**
   * Get the account number.
   */
  const getAccountNumber = () => accountNumber;

  /**
   * Get the next sequence number and increment the internal counter.
   */
  const getSequenceNumber = () => {
    const curr = sequenceNumber;
    sequenceNumber += 1n;
    return curr;
  };

  /**
   * Resync with the network (useful for error recovery).
   */
  const resync = async () => {
    const old = sequenceNumber;
    const account = await fetchAccount();
    sequenceNumber = account.sequence;
    log(
      `Resynced accountNumber ${accountNumber} sequence number from ${old} to ${sequenceNumber}`,
    );
  };

  return harden({
    getAccountNumber,
    getSequenceNumber,
    resync,
  });
};
```

</details>

File: packages/client-utils/src/smart-wallet-with-sequence.ts [hunk 12]
```diff
@@ -0,0 +1,223 @@
...
+    };
+
+    return queueOperation(operation, 'executeOffer', logPrefix);
+  };
+
+  return harden({
+    sendBridgeAction,
+    executeOffer,
+  });
+};
```
Comment (gibson042) [inline packages/client-utils/src/smart-wallet-with-sequence.ts]: I don't think it's a good idea to override SigningSmartWalletKit methods `sendBridgeAction` and `executeOffer` with incompatible replacements, which will make it unnecessarily difficult to integrate this behavior in the future. I'd much prefer to preserve compatibility, and also (since these methods should obviate the need to ever use the wrapped ones directly) prefer to return a SigningSmartWalletKit rather than the parts thereof:

<details>

```suggestion
type QueuedThunk<T> = {
  label: string;
  resolve: (value: T) => void;
  reject: (reason: unknown) => void;
  thunk: () => Promise<T>;
};

const isSequenceNumberMismatch = (error: Error | unknown) => {
  // @ts-expect-error reading "message" is fine here
  const message = error?.message || `${error}`;
  // *sigh*
  return message.includes('account sequence mismatch');
};

/**
 * Make a SigningSmartWalletKit with automatic management of outbound
 * transaction sequencing:
 * - Queue-based transaction serialization to prevent sequence conflicts
 * - Automatic error recovery for sequence mismatches
 * - Network sync on sequence errors with retry logic
 *
 * @alpha
 */
export const makeSequencingSmartWallet = (
  signingSmartWalletKit: SigningSmartWalletKit,
  txSequencer: TxSequencer,
  { log = () => {} }: { log?: (...args: unknown[]) => void },
): SigningSmartWalletKit => {
  // We only override `executeOffer` and `sendBridgeAction`, so ensure that
  // there are no unknown properties which could potentially bypass them.
  const {
    query,
    address,
    executeOffer: _unsafeExecuteOffer,
    sendBridgeAction: unsafeSendBridgeAction,
    ...swk
  } = signingSmartWalletKit;
  ({
    query,
    address,
    executeOffer: _unsafeExecuteOffer,
    sendBridgeAction: unsafeSendBridgeAction,
  }) satisfies Omit<SigningSmartWalletKit, keyof SmartWalletKit>;

  const chainId = swk.networkConfig.chainName;
  const accountNumber = Number(txSequencer.getAccountNumber());
  const makeSignerData = (label: string): SignerData => {
    const sequence = Number(txSequencer.getSequenceNumber());
    const signerData: SignerData = { accountNumber, sequence, chainId };
    log(`${label} signerData:`, signerData);
    return signerData;
  };

  // XXX There is no limit on queue growth.
  const queue = [] as QueuedThunk<unknown>[];
  let isDraining = false;

  /**
   * Run a thunk, retrying if it results in a sequence number mismatch error
   * (but only retrying at most once).
   */
  const runResyncable = async <T>(
    label: string,
    thunk: () => Promise<T>,
  ): Promise<T> => {
    await null;
    try {
      return await thunk();
    } catch (error) {
      if (isSequenceNumberMismatch(error)) {
        log(`${label} retrying with resynced sequence number`, error);
        await txSequencer.resync();
        try {
          return await thunk();
        } catch (retryError) {
          log(`${label} retry failed`, retryError);
          throw retryError;
        }
      }
      throw error;
    }
  };

  /**
   * Sequentially drain the queue.
   */
  const drainQueue = async (): Promise<void> => {
    await null;
    log(`Draining ${queue.length} operations`);
    while (queue.length > 0) {
      const { label, resolve, reject, thunk } = queue.shift()!;
      log(`${label} processing, ${queue.length} remaining`);
      try {
        const result = await runResyncable(label, thunk);
        log(`${label} completed`);
        resolve(result);
      } catch (error) {
        log(`${label} failed:`, error);
        reject(error);
      }
    }
  };

  /**
   * Enqueue a thunk for sequential execution.
   */
  const enqueue = <T>(label: string, thunk: () => Promise<T>): Promise<T> => {
    const nextIndex = queue.length;
    const resultP = new Promise<T>((resolve, reject) => {
      queue.push({ label, resolve, reject, thunk });
    });
    log(`${label} enqueued at index ${nextIndex}`);
    if (!isDraining) {
      isDraining = true;
      void drainQueue().finally(() => {
        isDraining = false;
      });
    }
    return resultP;
  };

  /**
   * Send a bridge action with managed sequence number.
   */
  const sendBridgeAction: SigningSmartWalletKit['sendBridgeAction'] = async (
    action,
    fee,
    memo,
    manualSignerData,
  ) => {
    manualSignerData === undefined || Fail`manual signerData is not supported`;
    const label = 'sendBridgeAction';
    return enqueue(label, () => {
      const signerData = makeSignerData(label);
      return unsafeSendBridgeAction(action, fee, memo, signerData);
    });
  };

  /**
   * Execute an offer with managed sequence number.
   */
  const executeOffer: SigningSmartWalletKit['executeOffer'] = async offer => {
    const txId = offer.offerArgs?.txId;
    const label = `executeOffer${txId ? ` ${txId}` : ''}`;
    return enqueue(label, async () => {
      const signerData = makeSignerData(label);
      const action: BridgeAction = { method: 'executeOffer', offer };
      const offerP = swk.pollOffer(address, offer.id);
      await unsafeSendBridgeAction(action, undefined, undefined, signerData);
      return offerP;
    });
  };

  const sequencingSmartWallet = {
    ...swk,
    query,
    address,
    executeOffer,
    sendBridgeAction,
  };
  return harden(sequencingSmartWallet);
};
```

</details>

File: packages/client-utils/test/sequence-manager.test.ts [hunk 13]
```diff
@@ -0,0 +1,108 @@
...
+  };
+
+  return {
+    fetch,
+    updateSequence: (newSequence: string) => {
+      mockSequence = newSequence;
+    },
+    getCallCount: () => callCount,
+  };
+};
```
Comment (gibson042) [inline packages/client-utils/test/sequence-manager.test.ts]: Nit: Rather than hard-coding the mocked data, it should be fully configurable for better locality in the test functions.
```suggestion
const createMockFetchAccountInfo = (
  accountNumber: `${bigint}`,
  sequenceNumber: `${bigint}`,
) => {
  let callCount = 0;

  const fetch = async (address: string): Promise<AccountResponse> => {
    callCount += 1;
    return {
      account: {
        '@type': '/cosmos.auth.v1beta1.BaseAccount',
        address,
        account_number: accountNumber,
        sequence: sequenceNumber,
      },
    };
  };

  return {
    fetch,
    setSequenceNumber: (newSequenceNumber: `${bigint}`) => {
      sequenceNumber = newSequenceNumber;
    },
    getCallCount: () => callCount,
  };
};
```

File: packages/client-utils/test/smart-wallet-with-sequence.test.ts [hunk 14]
```diff
@@ -0,0 +1,188 @@
...
+  };
+
+  return {
+    fetch,
+    updateSequence: (newSequence: string) => {
+      mockSequence = newSequence;
+    },
+    getNetworkSequence: () => Number(mockSequence),
+  };
+};
```
Comment (gibson042) [inline packages/client-utils/test/smart-wallet-with-sequence.test.ts]:
```suggestion
const createMockFetchAccountInfo = (
  accountNumber: `${bigint}`,
  sequenceNumber: `${bigint}`,
) => {
  const fetch = async (address: string): Promise<AccountResponse> => {
    return {
      account: {
        '@type': '/cosmos.auth.v1beta1.BaseAccount',
        address,
        account_number: accountNumber,
        sequence: sequenceNumber,
      },
    };
  };

  return {
    fetch,
    setSequenceNumber: (newSequenceNumber: `${bigint}`) => {
      sequenceNumber = newSequenceNumber;
    },
    getNetworkSequence: () => Number(sequenceNumber),
  };
};
```

File: packages/client-utils/test/smart-wallet-with-sequence.test.ts [hunk 15]
```diff
@@ -0,0 +1,188 @@
...
+
+  private shouldSimulateSequenceConflicts = false;
+
+  constructor(getNetworkSequence: () => number) {
+    this.networkSequence = getNetworkSequence;
+  }
+
+  enableSequenceConflictSimulation() {
+    this.shouldSimulateSequenceConflicts = true;
+  }
```
Comment (gibson042) [inline packages/client-utils/test/smart-wallet-with-sequence.test.ts]: Should `shouldSimulateSequenceConflicts` be a constructor option rather than dynamically under the control of a method?

File: packages/client-utils/test/smart-wallet-with-sequence.test.ts [hunk 16]
```diff
@@ -0,0 +1,188 @@
...
+  results.forEach((result: any) => {
+    t.is(result.code, 0);
+    t.truthy(result.transactionHash);
+  });
+
+  const submittedTransactions = mockWallet.getSubmittedTransactions();
+  t.is(submittedTransactions.length, 4);
+
+  const sequences = submittedTransactions.map(tx => tx.sequence);
+  t.deepEqual(sequences, [100, 101, 102, 103]);
```
Comment (gibson042) [inline packages/client-utils/test/smart-wallet-with-sequence.test.ts]: See [packages/internal/tools/ava-assertions.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/internal/tools/ava-assertions.js):
```suggestion
  arrayIsLike(t, results, [
    // prettier-ignore
    { code: 0, transactionHash: 'hash_sendBridgeAction_100', height: 3321451, sequence: 100 },
    // prettier-ignore
    { code: 0, transactionHash: 'hash_sendBridgeAction_101', height: 3321452, sequence: 101 },
    // prettier-ignore
    { code: 0, transactionHash: 'hash_test_102', height: 3321453, sequence: 102 },
    // prettier-ignore
    { code: 0, transactionHash: 'hash_sendBridgeAction_103', height: 3321454, sequence: 103 },
  ]);
  
  const submittedTransactions = mockWallet.getSubmittedTransactions();
  arrayIsLike(t, submittedTransactions, [
    { method: 'sendBridgeAction', sequence: 100 },
    { method: 'sendBridgeAction', sequence: 101 },
    { method: 'test', sequence: 102 },
    { method: 'sendBridgeAction', sequence: 103 },
  ]);
```

File: packages/client-utils/test/smart-wallet-with-sequence.test.ts [hunk 17]
```diff
@@ -0,0 +1,188 @@
...
+  );
+
+  mockFetch.updateSequence('105');
+
+  const result = (await walletWithSequence.executeOffer({
+    id: 'offer1',
+  } as any)) as any;
+
+  t.is(result.code, 0);
+  t.truthy(result.transactionHash);
```
Comment (gibson042) [inline packages/client-utils/test/smart-wallet-with-sequence.test.ts]:
```suggestion
  t.deepEqual(result, {
    code: 0,
    height: 3321451,
    transactionHash: `hash_sendBridgeAction_105`,
    sequence: 105,
  });
```

File: packages/client-utils/test/smart-wallet-with-sequence.test.ts [hunk 18]
```diff
@@ -0,0 +1,188 @@
...
+
+  t.true(logs.some(v => v.includes('Sequence error detected')));
+  t.true(logs.some(v => v.includes('Synced sequence: 101 → 105')));
+
+  const submittedTransactions = mockWallet.getSubmittedTransactions();
+  t.is(submittedTransactions.length, 1);
+  t.is(submittedTransactions[0].sequence, 105);
```
Comment (gibson042) [inline packages/client-utils/test/smart-wallet-with-sequence.test.ts]:
```suggestion
  const submittedTransactions = mockWallet.getSubmittedTransactions();
  arrayIsLike(t, submittedTransactions, [
    { method: 'sendBridgeAction', sequence: 105 },
  ]);
```

File: services/ymax-planner/src/cosmos-rest-client.ts [hunk 19]
```diff
@@ -212,6 +213,25 @@ export class CosmosRestClient {
     );
   }
 
+  async getAccountSequence(
```
Comment (gibson042) [inline services/ymax-planner/src/cosmos-rest-client.ts:216]: I'm trying to phase out this file in favor of services/ymax-planner/src/cosmos-rpc.ts; can we implement this functionality on top of that instead?
```ts
  await rpc
    .request('abci_query', {
      path: '/cosmos.auth.v1beta1.Query/Account',
      data: toHex(QueryAccountRequest.encode({ address }).finish()),
    })
    .then(respContainer =>
      QueryAccountResponse.decode(decodeBase64(respContainer.response.value)),
    );
```
(and we might be able to simplify such consumption even further; I've asked @michaelfig if we already have e.g. lookup tables or other helpers)

File: services/ymax-planner/src/main.ts [hunk 20]
```diff
@@ -105,7 +120,7 @@ export type SimplePowers = {
 };
 
 export const main = async (
-  args: string[],
+  argsArr: string[],
```
Comment (gibson042) [inline services/ymax-planner/src/main.ts]:
```suggestion
  cliArgs: string[],
```

File: services/ymax-planner/src/main.ts [hunk 21]
```diff
@@ -218,6 +233,37 @@ export const main = async (
     makeNonce: () => new Date(now()).toISOString(),
   });
 
+  const fetchAccountInfo: FetchAccountInfo = async address => {
+    return cosmosRest.getAccountSequence('agoric', address);
+  };
+
+  const sequenceManager = await makeSequenceManager(
+    {
+      log: (...args) => console.log('[SequenceManager]:', ...args),
```
Comment (gibson042) [inline services/ymax-planner/src/main.ts]:
```suggestion
      log: (...args) => console.log('[TxSequencer]', ...args),
```

File: services/ymax-planner/src/main.ts [hunk 22]
```diff
@@ -218,6 +233,37 @@ export const main = async (
...
+      address: signingSmartWalletKit.address,
+      fetchAccountInfo,
+    },
+  );
+
+  const smartWalletWithSequence = makeSmartWalletWithSequence(
+    {
+      signingSmartWalletKit,
+      sequenceManager,
+      log: (...args) => console.log('[SmartWalletWithSequence]:', ...args),
```
Comment (gibson042) [inline services/ymax-planner/src/main.ts]:
```suggestion
      log: (...args) => console.log('[SigningSmartWallet]', ...args),
```
But also, this seems likely to be excessively noisy. I wonder if most of the logging from `makeSmartWalletWithSequence` should be hidden behind a `verbose` option.

File: services/ymax-planner/src/main.ts [hunk 23]
```diff
@@ -218,6 +233,37 @@ export const main = async (
...
+    { chainId: networkConfig.chainName },
+  );
+
+  // create a wrapper that uses SmartWalletWithSequence methods
+  const smartWalletKitWithSequence: SmartWalletKitWithSequence = {
+    ...signingSmartWalletKit,
+    // override the three main methods to use SmartWalletWithSequence
+    sendBridgeAction: smartWalletWithSequence.sendBridgeAction,
+    executeOffer: smartWalletWithSequence.executeOffer,
+  };
```
Comment (gibson042) [inline services/ymax-planner/src/main.ts]: This is a smell (and inaccurately refers to "**three** main methods"); see my suggestion about the function in smart-wallet-with-sequence.ts returning an actual SigningSmartWallet rather than its component functions.

File: services/ymax-planner/src/pending-tx-manager.ts
Comment (gibson042) [inline services/ymax-planner/src/pending-tx-manager.ts:1]: I expect no changes in this file.

File: services/ymax-planner/src/resolver.ts
Comment (gibson042) [inline services/ymax-planner/src/resolver.ts:1]: I expect no changes in this file.

**Review by gibson042 — CHANGES_REQUESTED** [review]

File: services/ymax-planner/src/cosmos-rest-client.ts (hunk 19 above)
Comment (michaelfig) [reply services/ymax-planner/src/cosmos-rest-client.ts:216]: A codec registry (lookup table) is the way to go, but the helpers haven't been created yet.  The Telescope codegen used by client-utils and cosmic-proto might have some useful options to simplify, but I haven't explored that in quite some time.

File: packages/client-utils/src/sequence-manager.ts [hunk 24]
```diff
@@ -0,0 +1,59 @@
...
+  const getAccountNumber = () => accountNumber;
+
+  /**
+   * Get the next sequence number and increment the internal counter.
+   */
+  const getSequenceNumber = () => {
+    const curr = sequenceNumber;
+    sequenceNumber += 1n;
+    return curr;
+  };
```
Comment (gibson042) [inline packages/client-utils/src/sequence-manager.ts:43]: On second thought, I don't think a function with side effects that modify internal state should be named "get". It's really analogous to an Iterator `next` method.
```suggestion
  /**
   * Return the sequence number expected for the next transaction and increment
   * the internal counter for subsequent invocations.
   */
  const nextSequenceNumber = () => {
    const curr = sequenceNumber;
    sequenceNumber += 1n;
    return curr;
  };
```

File: packages/client-utils/src/sequence-manager.ts [hunk 25]
```diff
@@ -0,0 +1,59 @@
...
+ *
+ * @alpha
+ */
+export const makeTxSequencer = async (
+  fetchAccount: () => Promise<BaseAccount>,
+  { log = () => {} }: { log?: (...args: unknown[]) => void },
+): Promise<TxSequencer> => {
+  const initial = await fetchAccount();
+  const accountNumber: bigint = initial.accountNumber;
+  let sequenceNumber: bigint = initial.sequence;
```
Comment (gibson042) [inline packages/client-utils/src/sequence-manager.ts]: Suggestion for internal clarity:
```suggestion
  /** The sequence number to be included in the next transaction. */
  let nextSequenceNumber: bigint = initial.sequence;
```

File: packages/client-utils/src/smart-wallet-with-sequence.ts [hunk 26]
```diff
@@ -0,0 +1,182 @@
...
+  reject: (reason: unknown) => void;
+  thunk: () => Promise<T>;
+};
+
+const isSequenceNumberMismatch = (error: Error | unknown) => {
+  // @ts-expect-error reading "message" is fine here
+  const message = error?.message || `${error}`;
+  // *sigh*
+  return message.includes('account sequence mismatch');
+};
```
Comment (gibson042) [inline packages/client-utils/src/smart-wallet-with-sequence.ts]: I think we can do better, since ["account sequence mismatch" errors](https://github.com/agoric-labs/cosmos-sdk/blob/6ea4a76d5731effeb2594ac98dbcd8ec0a53556e/x/auth/ante/sigverify.go#L292) are associated with `sdkerrors.ErrWrongSequence` ([codespace "sdk" with number 32](https://github.com/agoric-labs/cosmos-sdk/blob/6ea4a76d5731effeb2594ac98dbcd8ec0a53556e/types/errors/errors.go#L106-L108), [propagated by cosmjs](https://github.com/cosmos/cosmjs/blob/b00ff7f9cde2d32f1fbbb91c160130c9f9c81a76/packages/stargate/src/stargateclient.ts#L490) and visible in our logs).
```suggestion
const isSequenceNumberMismatch = (error: BroadcastTxError | Error | unknown) =>
  // https://cosmos.github.io/cosmjs/latest/stargate/classes/BroadcastTxError.html
  error instanceof BroadcastTxError &&
  // https://pkg.go.dev/github.com/cosmos/cosmos-sdk/types/errors#pkg-variables:~:text=ErrWrongSequence
  error.codespace === 'sdk' &&
  error.code === 32;
```

File: packages/client-utils/test/sequence-manager.test.ts [hunk 27]
```diff
@@ -0,0 +1,67 @@
...
+  const mockFetch = createMockFetchAccount(377n, 100n);
+  const logs: string[] = [];
+
+  const sequencer = await makeTxSequencer(mockFetch.fetch, {
+    log: (...args: any[]) => logs.push(args.join(' ')),
+  });
+
+  // Use some sequences
+  sequencer.getSequenceNumber(); // 100
+  sequencer.getSequenceNumber(); // 101
```
Comment (gibson042) [inline packages/client-utils/test/sequence-manager.test.ts]:
```suggestion
  // Use some sequences
  t.is(sequencer.getSequenceNumber(), 100n);
  t.is(sequencer.getSequenceNumber(), 101n);
```

File: packages/client-utils/test/smart-wallet-with-sequence.test.ts [hunk 28]
```diff
@@ -0,0 +1,171 @@
...
+
+class MockSigningSmartWalletKit {
+  private submittedTransactions: Array<{
+    method: string;
+    sequence: bigint;
+  }> = [];
+
+  private networkSequence: () => bigint;
+
+  private shouldSimulateSequenceConflicts: boolean;
```
Comment (gibson042) [inline packages/client-utils/test/smart-wallet-with-sequence.test.ts]: We avoid TypeScript `private` annotations, even in test code... I think these should be actual private fields.
```suggestion
  #submittedTransactions: Array<{
    method: string;
    sequence: bigint;
  }> = [];

  #networkSequence: () => bigint;

  #shouldSimulateSequenceConflicts: boolean;
```

File: packages/client-utils/test/smart-wallet-with-sequence.test.ts [hunk 29]
```diff
@@ -0,0 +1,171 @@
...
+    const currentNetworkSequence = this.networkSequence();
+
+    // Simulate sequence mismatch if enabled and sequence is out of sync
+    if (
+      this.shouldSimulateSequenceConflicts &&
+      signerData.sequence < currentNetworkSequence
+    ) {
+      throw new Error(
+        `Broadcasting transaction failed with code 32 (codespace: sdk). Log: account sequence mismatch, expected ${currentNetworkSequence}, got ${signerData.sequence}: incorrect account sequence`,
+      );
```
Comment (gibson042) [inline packages/client-utils/test/smart-wallet-with-sequence.test.ts]:
```suggestion
      const log = `account sequence mismatch, expected ${currentNetworkSequence}, got ${signerData.sequence}: incorrect account sequence`;
      throw new BroadcastTxError(32, 'sdk', log);
```

File: packages/client-utils/test/smart-wallet-with-sequence.test.ts [hunk 30]
```diff
@@ -0,0 +1,171 @@
...
+      height: 3321450 + this.submittedTransactions.length,
+      transactionHash: `hash_${method}_${signerData.sequence}`,
+      sequence: signerData.sequence,
+    };
+  }
+
+  async pollOffer(_address: string, _offerId: string) {
+    void this.submittedTransactions;
+    return { status: 'accepted' };
+  }
```
Comment (gibson042) [inline packages/client-utils/test/smart-wallet-with-sequence.test.ts]:
```suggestion
  async pollOffer(_address: string, _offerId: string) {
    return { status: 'accepted' };
  }
```

File: services/ymax-planner/src/main.ts [hunk 31]
```diff
@@ -218,6 +221,28 @@ export const main = async (
     makeNonce: () => new Date(now()).toISOString(),
   });
 
+  const fetchAccount = async () => {
+    const response = await cosmosRest.getAccountSequence('agoric', signingSmartWalletKit.address);
+    const { account } = response as any;
```
Comment (gibson042) [inline services/ymax-planner/src/main.ts]: I foresee this `as any` getting us into trouble; can `getAccountSequence` specify a more precise return type? I'd look in packages/client-utils/dist/codegen and packages/cosmic-proto.

File: services/ymax-planner/src/main.ts [hunk 32]
```diff
@@ -218,6 +221,28 @@ export const main = async (
...
+    log: (...args) => console.log('[TxSequencer]:', ...args),
+  });
+
+  const smartWalletKitWithSequence = makeSequencingSmartWallet(
+    signingSmartWalletKit,
+    txSequencer,
+    {
+      log: (...args) => console.log('[SequencingSmartWallet]:', ...args),
+    },
+  );
```
Comment (gibson042) [inline services/ymax-planner/src/main.ts:225]: https://github.com/Agoric/agoric-sdk/pull/11968#discussion_r2516419385
> this seems likely to be excessively noisy. I wonder if most of the logging from `makeSmartWalletWithSequence` should be hidden behind a `verbose` option.

File: services/ymax-planner/test/mocks.ts [hunk 33]
```diff
@@ -354,3 +393,89 @@ export const createMockGmpExecutionEvent = (txId: string) => {
...
+  private submittedTransactions: Array<{
+    method: string;
+    sequence: number;
+    timestamp: number;
+  }> = [];
+  private networkSequence: () => number;
+  private shouldSimulateSequenceConflicts = false;
+  private networkDelay = 20;
+  private mockTime = 1234567890000;
+  private sequenceCounter = 0;
```
Comment (gibson042) [inline services/ymax-planner/test/mocks.ts]:
```suggestion
  #submittedTransactions: Array<{
    method: string;
    sequence: number;
    timestamp: number;
  }> = [];
  #networkSequence: () => number;
  #shouldSimulateSequenceConflicts = false;
  #networkDelay = 20;
  #mockTime = 1234567890000;
  #sequenceCounter = 0;
```

File: services/ymax-planner/test/mocks.ts [hunk 34]
```diff
@@ -354,3 +393,89 @@ export const createMockGmpExecutionEvent = (txId: string) => {
...
   };
 };
+
+type SubmitTxResponse = {
+  code: number;
+  height: number;
+  transactionHash: string;
+  sequence: number;
+};
+export class MockSigningSmartWalletKit {
```
Comment (gibson042) [inline services/ymax-planner/test/mocks.ts]: Please align better with packages/client-utils/test/smart-wallet-with-sequence.test.ts (ideally removing any duplication altogether).

**Review by gibson042 — APPROVED** [review]
LGTM after addressing this final batch of suggestions.
